// Textos del formulario de pre-check-in (/precheckin) en los cuatro idiomas.
//
// Una clave = el mismo texto en todos los idiomas. El castellano es el
// original y NO se toca: está escrito con cuidado y va a un parte policial.
// Lo que cambia con el idioma son sólo las ETIQUETAS; los valores que se
// guardan (códigos de documento, sexo, país, parentesco, fechas) son siempre
// los mismos.
//
// `{nombre}` dentro de un texto se sustituye al pintarlo (ver `traductor`).

export const IDIOMAS = ['es', 'en', 'de', 'fr'];

/** Para fechas y orden alfabético de países. */
export const LOCALES = { es: 'es-ES', en: 'en-GB', de: 'de-DE', fr: 'fr-FR' };

/** Cómo se llama cada idioma en su propia lengua (para el selector). */
export const NOMBRES_IDIOMA = { es: 'Español', en: 'English', de: 'Deutsch', fr: 'Français' };

export const TEXTOS = {
    es: {
        meta_titulo: 'Tus datos antes de llegar — Apartamentos Tío José María',
        meta_descripcion: 'Registro de viajeros obligatorio (Real Decreto 933/2021).',
        idioma: 'Idioma',
        inicio: 'Inicio',
        persona_de: 'Persona {n} de {total}',
        ultimo_paso: 'Último paso',
        cargando: 'Cargando tu reserva…',
        un_momento: 'Un momento',
        atras: 'Atrás',
        guardar: 'Guardar',
        repasar: 'Repasar',
        siguiente: 'Siguiente',
        guardando: 'Guardando…',
        enviar: 'Enviar mis datos',
        guardado_aviso: 'Guardado en este móvil. Vuelve al mismo enlace cuando quieras y sigues donde lo dejaste.',

        // Al abrir el enlace
        err_enlace: 'El enlace no es válido. Revisa el correo de confirmación o escríbenos.',
        err_no_encontrada: 'No encontramos esa reserva. Revisa el enlace o escríbenos.',
        err_cancelada: 'Esta reserva está cancelada. Si crees que es un error, escríbenos.',
        err_sin_confirmar: 'Esta reserva todavía no está confirmada. Termina el pago primero.',
        err_pasada: 'Esta estancia ya ha terminado. Si necesitas algo, escríbenos.',
        abre_sin_fecha: 'Este formulario se abre una semana antes de tu llegada. Te avisaremos por correo.',
        abre_con_fecha: 'Este formulario se abre una semana antes de tu llegada: el {fecha}. Te avisaremos por correo.',

        // Al enviar
        env_pronto: 'Todavía es pronto. Se abre una semana antes de tu llegada.',
        env_sin_confirmar: 'La reserva no está confirmada todavía.',
        env_pasada: 'Esa reserva ya ha terminado.',
        env_fallo: 'No hemos podido guardarlo. Prueba otra vez en un momento o escríbenos.',

        // Plurales y piezas sueltas
        personas_1: '{n} persona',
        personas_n: '{n} personas',
        persona_n: 'Persona {n}',
        una_persona: 'una persona',
        y: 'y',
        anos: '{n} años',

        // Portada
        portada_titulo: 'Tus datos antes de llegar',
        portada_intro: 'El alojamiento está obligado por ley a registrar los datos de todas las personas que duermen aquí, y a nosotros nos toca pedírtelos. Se rellena una vez, en un par de minutos, y así en la entrada sólo nos damos la bienvenida.',
        tu_reserva: 'Tu reserva',
        fechas_reserva: 'Del {entrada} al {salida} · {personas}',
        ya_empezado: 'Ya habías empezado. Seguimos donde lo dejaste.',
        ya_hay_todas: 'Ya tenemos los datos de {nombres} ({rellenas} de {total}). Si viene alguien más, añade aquí sus datos; si no, no hace falta nada.',
        ya_hay_falta_1: 'Ya tenemos los datos de {nombres} ({rellenas} de {total}). Falta 1 persona: rellena la tuya.',
        ya_hay_faltan: 'Ya tenemos los datos de {nombres} ({rellenas} de {total}). Faltan {faltan} personas: rellena la tuya.',
        portada_privacidad: 'Sólo se usan para cumplir esa obligación. No se comparten con nadie más.',
        portada_medias: 'Puedes dejarlo a medias: lo que escribas se queda guardado en este móvil.',
        portada_varios: 'Puedes rellenar a todos desde este móvil, o que cada uno lo haga desde el suyo con este mismo enlace.',
        empezar: 'Empezar',

        // Ficha de cada persona
        tus_datos: 'Tus datos',
        quitar: 'Quitar',
        sub_titular: 'Empezamos por quien reserva.',
        sub_segundo_movil: 'Los tuyos. Los de quien reservó ya los tenemos.',
        sub_acompanante: 'Los datos de cada persona que duerme aquí, también los niños.',
        quitar_ayuda: 'Si prefiere rellenarlo ella misma desde su móvil con el mismo enlace, toca «Quitar»: su ficha no se pierde, la hace ella.',
        nombre: 'Nombre',
        apellido1: 'Primer apellido',
        apellido2: 'Segundo apellido',
        apellido2_ayuda: 'Si no tienes, déjalo en blanco.',
        sexo: 'Sexo',
        sexo_H: 'Hombre',
        sexo_M: 'Mujer',
        sexo_X: 'Prefiero no decirlo',
        fecha_nac: 'Fecha de nacimiento',
        tipo_doc: 'Tipo de documento',
        num_doc: 'Número del documento',
        soporte: 'Número de soporte',
        soporte_ayuda: 'En el DNI español está detrás, arriba a la derecha, y empieza por letras. En el NIE, en el mismo sitio. Con otros documentos, déjalo en blanco.',
        nacionalidad: 'Nacionalidad',
        donde_vives: 'Dónde vives habitualmente',
        calle: 'Calle y número',
        municipio: 'Pueblo o ciudad',
        municipio_ayuda: 'Empieza a escribir y elígelo de la lista.',
        cp: 'Código postal',
        pais: 'País',
        localizarte: 'Cómo localizarte',
        movil: 'Teléfono móvil',
        email: 'Correo electrónico',
        aviso_menor: 'Al ser menor de edad no hace falta su documento. Al final te preguntamos con quién viene.',
        aviso_menor14: 'Al ser menor de 14 años no tiene que firmar: sus datos los das tú.',
        firma: 'Tu firma',
        firma_ayuda: 'Firma con el dedo dentro del recuadro. La ley pide la firma de todos los mayores de 14 años.',
        paises_frecuentes: 'Los más habituales',
        paises_todos: 'Todos los países',

        // Tipos de documento (el código no cambia)
        doc_D: 'DNI español',
        doc_P: 'Pasaporte',
        doc_N: 'NIE / tarjeta de residencia',
        doc_E: 'Documento de identidad de otro país',
        doc_C: 'Permiso de conducir de la UE',
        doc_X: 'Otro documento oficial',

        // Lo que falta en una ficha
        err_nombre: 'Pon el nombre',
        err_apellido1: 'Pon el primer apellido',
        err_sexo: 'Elige una opción',
        err_fecha: 'Pon la fecha de nacimiento',
        err_fecha_futura: 'Esa fecha todavía no ha llegado',
        err_pais: 'Elige el país',
        err_calle: 'Pon la calle y el número',
        err_municipio: 'Pon el pueblo o la ciudad',
        err_documento: 'Pon el número del documento',
        err_soporte: 'Con DNI o NIE hace falta este número',
        err_apellido2: 'Con DNI o NIE hace falta el segundo apellido',
        err_firma: 'Falta la firma',
        err_movil: 'Pon un teléfono de contacto',

        // Firma
        firma_aria: 'Recuadro para firmar con el dedo',
        firma_recogida: 'Firma recogida',
        firma_aqui: 'Firma aquí con el dedo',
        borrar: 'Borrar',

        // Repaso
        repaso_titulo: 'Un último repaso',
        repaso_sub: 'Comprueba que están todas las personas que van a dormir aquí.',
        sin_nombre: 'Sin nombre',
        quien_reserva: 'Quien reserva',
        acompanante: 'Acompañante',
        faltan_cosas: 'Le faltan cosas',
        cambiar: 'Cambiar',
        quitar_a: 'Quitar a {nombre}',
        esta_persona: 'esta persona',
        anadir: 'Añadir otra persona',
        reserva_para: 'Tu reserva es para {personas}. Si vais a ser más, escríbenos antes de llegar.',
        incompletos_1: 'Hay {n} persona a las que les falta algo. Toca «Cambiar» para terminarlas.',
        incompletos_n: 'Hay {n} personas a las que les falta algo. Toca «Cambiar» para terminarlas.',
        acepto_antes: 'Los datos son ciertos y sé que el alojamiento tiene que comunicarlos a las autoridades, como manda el Real Decreto 933/2021. He leído la ',
        acepto_enlace: 'política de privacidad',
        acepto_despues: '.',

        // Menores
        menores_titulo: 'Quién viene con los peques',
        menores_sub: 'Cuando viaja un menor, la ley nos pide saber qué es de él la persona adulta que lo acompaña.',
        menor_sin_adulto: 'Tiene que ir con una persona mayor de edad. Añádela arriba.',
        con_quien: '¿Con quién viene?',
        rel_etiqueta: '{adulto} es de {menor}…',
        esa_persona: 'Esa persona',
        elige_opcion: 'Elige una opción…',
        falta_asignar: 'Dinos con quién viene.',
        falta_relacion: 'Dinos qué es esa persona de él.',

        // Parentesco, dicho desde el adulto (el código no cambia)
        par_PA: 'Su padre o su madre',
        par_AB: 'Su abuelo o su abuela',
        par_HR: 'Su hermano o su hermana',
        par_TI: 'Su tío o su tía',
        par_TU: 'Su tutor o su tutora',
        par_SB: 'Su sobrino o su sobrina',
        par_NI: 'Su nieto o su nieta',
        par_HJ: 'Su hijo o su hija',
        par_BA: 'Su bisabuelo o su bisabuela',
        par_BN: 'Su bisnieto o su bisnieta',
        par_CY: 'Su cónyuge',
        par_CD: 'Su cuñado o su cuñada',
        par_SG: 'Su suegro o su suegra',
        par_YN: 'Su yerno o su nuera',
        par_OT: 'Otra cosa',

        // Quién ha pagado
        pagador_titulo: '¿Quién ha pagado?',
        pagador_sub: 'Nos lo piden junto con el resto de datos. Basta con el nombre de quien hizo el pago.',
        pagado_yo: 'Lo he pagado yo',
        pagado_otra: 'Lo ha pagado otra persona',
        como_se_llama: '¿Cómo se llama?',

        // Terminado
        listo: 'Listo, muchas gracias',
        terminado_antes: 'Tenemos los datos de {personas} para la reserva ',
        terminado_despues: '. En la entrada sólo tienes que venir con el documento por si hay que comprobarlo.',
        terminado_error: 'Si te has equivocado en algo, vuelve a este mismo enlace y mándalo otra vez.',
        volver: 'Volver al inicio',
    },

    en: {
        meta_titulo: 'Your details before you arrive — Apartamentos Tío José María',
        meta_descripcion: 'Mandatory guest registration (Royal Decree 933/2021).',
        idioma: 'Language',
        inicio: 'Home',
        persona_de: 'Person {n} of {total}',
        ultimo_paso: 'Last step',
        cargando: 'Loading your booking…',
        un_momento: 'Just a moment',
        atras: 'Back',
        guardar: 'Save',
        repasar: 'Review',
        siguiente: 'Next',
        guardando: 'Saving…',
        enviar: 'Send my details',
        guardado_aviso: 'Saved on this phone. Come back to the same link whenever you like and pick up where you left off.',

        err_enlace: 'This link is not valid. Check your confirmation email or write to us.',
        err_no_encontrada: 'We can\'t find that booking. Check the link or write to us.',
        err_cancelada: 'This booking has been cancelled. If you think this is a mistake, write to us.',
        err_sin_confirmar: 'This booking is not confirmed yet. Please complete the payment first.',
        err_pasada: 'This stay has already ended. If you need anything, write to us.',
        abre_sin_fecha: 'This form opens one week before you arrive. We\'ll let you know by email.',
        abre_con_fecha: 'This form opens one week before you arrive: on {fecha}. We\'ll let you know by email.',

        env_pronto: 'It\'s still too early. The form opens one week before you arrive.',
        env_sin_confirmar: 'The booking is not confirmed yet.',
        env_pasada: 'That booking has already ended.',
        env_fallo: 'We couldn\'t save it. Please try again in a moment or write to us.',

        personas_1: '{n} person',
        personas_n: '{n} people',
        persona_n: 'Person {n}',
        una_persona: 'one person',
        y: 'and',
        anos: '{n} years old',

        portada_titulo: 'Your details before you arrive',
        portada_intro: 'By law, the accommodation must register the details of everyone who sleeps here, so we have to ask you for them. You fill it in once, in a couple of minutes, and then at check-in all that\'s left is to say hello.',
        tu_reserva: 'Your booking',
        fechas_reserva: '{entrada} to {salida} · {personas}',
        ya_empezado: 'You had already started. We\'ll pick up where you left off.',
        ya_hay_todas: 'We already have the details of {nombres} ({rellenas} of {total}). If someone else is coming, add their details here; if not, there\'s nothing more to do.',
        ya_hay_falta_1: 'We already have the details of {nombres} ({rellenas} of {total}). 1 person is missing: fill in yours.',
        ya_hay_faltan: 'We already have the details of {nombres} ({rellenas} of {total}). {faltan} people are missing: fill in yours.',
        portada_privacidad: 'They are only used to meet that obligation. They are not shared with anyone else.',
        portada_medias: 'You can stop halfway: whatever you type stays saved on this phone.',
        portada_varios: 'You can fill in everyone from this phone, or each person can do it from their own phone with this same link.',
        empezar: 'Start',

        tus_datos: 'Your details',
        quitar: 'Remove',
        sub_titular: 'We start with the person who booked.',
        sub_segundo_movil: 'Yours. We already have the details of the person who booked.',
        sub_acompanante: 'The details of each person sleeping here, children included.',
        quitar_ayuda: 'If this person would rather fill it in on their own phone with the same link, tap «Remove»: nothing is lost, they fill in their own form.',
        nombre: 'First name',
        apellido1: 'Surname',
        apellido2: 'Second surname',
        apellido2_ayuda: 'If you don\'t have one, leave it blank.',
        sexo: 'Sex',
        sexo_H: 'Male',
        sexo_M: 'Female',
        sexo_X: 'Prefer not to say',
        fecha_nac: 'Date of birth',
        tipo_doc: 'Type of document',
        num_doc: 'Document number',
        soporte: 'Support number',
        soporte_ayuda: 'On a Spanish DNI it is on the back, top right, and starts with letters. On an NIE, in the same place. With other documents, leave it blank.',
        nacionalidad: 'Nationality',
        donde_vives: 'Where you usually live',
        calle: 'Street and number',
        municipio: 'Town or city',
        municipio_ayuda: 'Start typing and pick it from the list.',
        cp: 'Postcode',
        pais: 'Country',
        localizarte: 'How to reach you',
        movil: 'Mobile phone',
        email: 'Email',
        aviso_menor: 'As a minor, they don\'t need to give an ID document. At the end we\'ll ask who they are travelling with.',
        aviso_menor14: 'As they are under 14, they don\'t have to sign: you give their details.',
        firma: 'Your signature',
        firma_ayuda: 'Sign with your finger inside the box. The law requires the signature of everyone aged 14 or over.',
        paises_frecuentes: 'Most common',
        paises_todos: 'All countries',

        doc_D: 'Spanish DNI',
        doc_P: 'Passport',
        doc_N: 'NIE / residence card',
        doc_E: 'ID card from another country',
        doc_C: 'EU driving licence',
        doc_X: 'Other official document',

        err_nombre: 'Enter the first name',
        err_apellido1: 'Enter the surname',
        err_sexo: 'Choose an option',
        err_fecha: 'Enter the date of birth',
        err_fecha_futura: 'That date hasn\'t happened yet',
        err_pais: 'Choose the country',
        err_calle: 'Enter the street and number',
        err_municipio: 'Enter the town or city',
        err_documento: 'Enter the document number',
        err_soporte: 'This number is required with a DNI or NIE',
        err_apellido2: 'The second surname is required with a DNI or NIE',
        err_firma: 'Signature missing',
        err_movil: 'Enter a contact phone number',

        firma_aria: 'Box to sign with your finger',
        firma_recogida: 'Signature saved',
        firma_aqui: 'Sign here with your finger',
        borrar: 'Clear',

        repaso_titulo: 'One last check',
        repaso_sub: 'Check that everyone who is going to sleep here is on the list.',
        sin_nombre: 'No name',
        quien_reserva: 'Person who booked',
        acompanante: 'Companion',
        faltan_cosas: 'Some details are missing',
        cambiar: 'Edit',
        quitar_a: 'Remove {nombre}',
        esta_persona: 'this person',
        anadir: 'Add another person',
        reserva_para: 'Your booking is for {personas}. If there will be more of you, write to us before you arrive.',
        incompletos_1: '{n} person is missing something. Tap «Edit» to finish.',
        incompletos_n: '{n} people are missing something. Tap «Edit» to finish them.',
        acepto_antes: 'The details are true, and I know that the accommodation has to report them to the authorities, as required by Royal Decree 933/2021. I have read the ',
        acepto_enlace: 'privacy policy',
        acepto_despues: '.',

        menores_titulo: 'Who is with the children',
        menores_sub: 'When a minor travels, the law requires us to know how the adult accompanying them is related to them.',
        menor_sin_adulto: 'They must travel with an adult. Add one above.',
        con_quien: 'Who are they travelling with?',
        rel_etiqueta: '{adulto} is {menor}\'s…',
        esa_persona: 'That person',
        elige_opcion: 'Choose an option…',
        falta_asignar: 'Tell us who they are travelling with.',
        falta_relacion: 'Tell us how that person is related to them.',

        par_PA: 'Father or mother',
        par_AB: 'Grandfather or grandmother',
        par_HR: 'Brother or sister',
        par_TI: 'Uncle or aunt',
        par_TU: 'Legal guardian',
        par_SB: 'Nephew or niece',
        par_NI: 'Grandson or granddaughter',
        par_HJ: 'Son or daughter',
        par_BA: 'Great-grandfather or great-grandmother',
        par_BN: 'Great-grandson or great-granddaughter',
        par_CY: 'Spouse',
        par_CD: 'Brother-in-law or sister-in-law',
        par_SG: 'Father-in-law or mother-in-law',
        par_YN: 'Son-in-law or daughter-in-law',
        par_OT: 'Something else',

        pagador_titulo: 'Who paid?',
        pagador_sub: 'We are asked for this along with the rest of the details. The name of the person who made the payment is enough.',
        pagado_yo: 'I paid',
        pagado_otra: 'Someone else paid',
        como_se_llama: 'What is their name?',

        listo: 'All done, thank you very much',
        terminado_antes: 'We have the details of {personas} for booking ',
        terminado_despues: '. At check-in, just bring your ID document in case it needs to be checked.',
        terminado_error: 'If you got something wrong, come back to this same link and send it again.',
        volver: 'Back to home',
    },

    de: {
        meta_titulo: 'Ihre Daten vor der Anreise — Apartamentos Tío José María',
        meta_descripcion: 'Gesetzlich vorgeschriebene Gästeregistrierung (Königliches Dekret 933/2021).',
        idioma: 'Sprache',
        inicio: 'Startseite',
        persona_de: 'Person {n} von {total}',
        ultimo_paso: 'Letzter Schritt',
        cargando: 'Ihre Buchung wird geladen…',
        un_momento: 'Einen Moment',
        atras: 'Zurück',
        guardar: 'Speichern',
        repasar: 'Überprüfen',
        siguiente: 'Weiter',
        guardando: 'Wird gespeichert…',
        enviar: 'Meine Daten senden',
        guardado_aviso: 'Auf diesem Handy gespeichert. Öffnen Sie denselben Link, wann Sie möchten, und machen Sie dort weiter, wo Sie aufgehört haben.',

        err_enlace: 'Der Link ist ungültig. Prüfen Sie die Bestätigungs-E-Mail oder schreiben Sie uns.',
        err_no_encontrada: 'Wir finden diese Buchung nicht. Prüfen Sie den Link oder schreiben Sie uns.',
        err_cancelada: 'Diese Buchung ist storniert. Wenn Sie glauben, dass das ein Fehler ist, schreiben Sie uns.',
        err_sin_confirmar: 'Diese Buchung ist noch nicht bestätigt. Schließen Sie bitte zuerst die Zahlung ab.',
        err_pasada: 'Dieser Aufenthalt ist bereits beendet. Wenn Sie etwas brauchen, schreiben Sie uns.',
        abre_sin_fecha: 'Dieses Formular öffnet eine Woche vor Ihrer Anreise. Wir benachrichtigen Sie per E-Mail.',
        abre_con_fecha: 'Dieses Formular öffnet eine Woche vor Ihrer Anreise: am {fecha}. Wir benachrichtigen Sie per E-Mail.',

        env_pronto: 'Es ist noch zu früh. Das Formular öffnet eine Woche vor Ihrer Anreise.',
        env_sin_confirmar: 'Die Buchung ist noch nicht bestätigt.',
        env_pasada: 'Diese Buchung ist bereits beendet.',
        env_fallo: 'Wir konnten es nicht speichern. Versuchen Sie es gleich noch einmal oder schreiben Sie uns.',

        personas_1: '{n} Person',
        personas_n: '{n} Personen',
        persona_n: 'Person {n}',
        una_persona: 'einer Person',
        y: 'und',
        anos: '{n} Jahre',

        portada_titulo: 'Ihre Daten vor der Anreise',
        portada_intro: 'Die Unterkunft ist gesetzlich verpflichtet, die Daten aller Personen zu erfassen, die hier übernachten, und wir müssen Sie darum bitten. Sie füllen es einmal aus, in ein paar Minuten, und bei der Ankunft bleibt nur noch die Begrüßung.',
        tu_reserva: 'Ihre Buchung',
        fechas_reserva: '{entrada} bis {salida} · {personas}',
        ya_empezado: 'Sie hatten schon angefangen. Wir machen dort weiter, wo Sie aufgehört haben.',
        ya_hay_todas: 'Wir haben bereits die Daten von {nombres} ({rellenas} von {total}). Wenn noch jemand mitkommt, tragen Sie hier seine Daten ein; sonst ist nichts weiter nötig.',
        ya_hay_falta_1: 'Wir haben bereits die Daten von {nombres} ({rellenas} von {total}). Es fehlt 1 Person: Tragen Sie Ihre Daten ein.',
        ya_hay_faltan: 'Wir haben bereits die Daten von {nombres} ({rellenas} von {total}). Es fehlen {faltan} Personen: Tragen Sie Ihre Daten ein.',
        portada_privacidad: 'Sie werden nur zur Erfüllung dieser Pflicht verwendet. Sie werden mit niemandem sonst geteilt.',
        portada_medias: 'Sie können zwischendurch aufhören: Was Sie eingeben, bleibt auf diesem Handy gespeichert.',
        portada_varios: 'Sie können alle von diesem Handy aus eintragen, oder jede Person macht es auf ihrem eigenen Handy mit demselben Link.',
        empezar: 'Beginnen',

        tus_datos: 'Ihre Daten',
        quitar: 'Entfernen',
        sub_titular: 'Wir beginnen mit der Person, die gebucht hat.',
        sub_segundo_movil: 'Ihre eigenen. Die Daten der Person, die gebucht hat, haben wir schon.',
        sub_acompanante: 'Die Daten jeder Person, die hier übernachtet, auch der Kinder.',
        quitar_ayuda: 'Wenn diese Person es lieber selbst auf ihrem Handy mit demselben Link ausfüllt, tippen Sie auf «Entfernen»: Es geht nichts verloren, sie füllt ihr Formular selbst aus.',
        nombre: 'Vorname',
        apellido1: 'Nachname',
        apellido2: 'Zweiter Nachname',
        apellido2_ayuda: 'Wenn Sie keinen haben, lassen Sie das Feld leer.',
        sexo: 'Geschlecht',
        sexo_H: 'Mann',
        sexo_M: 'Frau',
        sexo_X: 'Keine Angabe',
        fecha_nac: 'Geburtsdatum',
        tipo_doc: 'Art des Dokuments',
        num_doc: 'Dokumentnummer',
        soporte: 'Support-Nummer (número de soporte)',
        soporte_ayuda: 'Beim spanischen DNI steht sie auf der Rückseite oben rechts und beginnt mit Buchstaben. Beim NIE an derselben Stelle. Bei anderen Dokumenten lassen Sie das Feld leer.',
        nacionalidad: 'Staatsangehörigkeit',
        donde_vives: 'Ihr gewöhnlicher Wohnsitz',
        calle: 'Straße und Hausnummer',
        municipio: 'Ort oder Stadt',
        municipio_ayuda: 'Beginnen Sie zu tippen und wählen Sie ihn aus der Liste.',
        cp: 'Postleitzahl',
        pais: 'Land',
        localizarte: 'So erreichen wir Sie',
        movil: 'Handynummer',
        email: 'E-Mail',
        aviso_menor: 'Da die Person minderjährig ist, ist kein Ausweisdokument nötig. Am Ende fragen wir, mit wem sie reist.',
        aviso_menor14: 'Da die Person unter 14 Jahre alt ist, muss sie nicht unterschreiben: Ihre Daten geben Sie an.',
        firma: 'Ihre Unterschrift',
        firma_ayuda: 'Unterschreiben Sie mit dem Finger im Feld. Das Gesetz verlangt die Unterschrift aller Personen ab 14 Jahren.',
        paises_frecuentes: 'Am häufigsten',
        paises_todos: 'Alle Länder',

        doc_D: 'Spanischer Personalausweis (DNI)',
        doc_P: 'Reisepass',
        doc_N: 'NIE / Aufenthaltskarte',
        doc_E: 'Personalausweis eines anderen Landes',
        doc_C: 'EU-Führerschein',
        doc_X: 'Anderes amtliches Dokument',

        err_nombre: 'Geben Sie den Vornamen ein',
        err_apellido1: 'Geben Sie den Nachnamen ein',
        err_sexo: 'Wählen Sie eine Option',
        err_fecha: 'Geben Sie das Geburtsdatum ein',
        err_fecha_futura: 'Dieses Datum liegt in der Zukunft',
        err_pais: 'Wählen Sie das Land',
        err_calle: 'Geben Sie Straße und Hausnummer ein',
        err_municipio: 'Geben Sie den Ort oder die Stadt ein',
        err_documento: 'Geben Sie die Dokumentnummer ein',
        err_soporte: 'Mit DNI oder NIE ist diese Nummer nötig',
        err_apellido2: 'Mit DNI oder NIE ist der zweite Nachname nötig',
        err_firma: 'Die Unterschrift fehlt',
        err_movil: 'Geben Sie eine Telefonnummer an',

        firma_aria: 'Feld zum Unterschreiben mit dem Finger',
        firma_recogida: 'Unterschrift erfasst',
        firma_aqui: 'Hier mit dem Finger unterschreiben',
        borrar: 'Löschen',

        repaso_titulo: 'Eine letzte Kontrolle',
        repaso_sub: 'Prüfen Sie, ob alle Personen dabei sind, die hier übernachten werden.',
        sin_nombre: 'Ohne Namen',
        quien_reserva: 'Hat gebucht',
        acompanante: 'Begleitperson',
        faltan_cosas: 'Es fehlen Angaben',
        cambiar: 'Ändern',
        quitar_a: '{nombre} entfernen',
        esta_persona: 'Diese Person',
        anadir: 'Weitere Person hinzufügen',
        reserva_para: 'Ihre Buchung gilt für {personas}. Wenn Sie mehr sind, schreiben Sie uns vor der Anreise.',
        incompletos_1: 'Bei {n} Person fehlt noch etwas. Tippen Sie auf «Ändern», um sie zu vervollständigen.',
        incompletos_n: 'Bei {n} Personen fehlt noch etwas. Tippen Sie auf «Ändern», um sie zu vervollständigen.',
        acepto_antes: 'Die Angaben sind wahr, und mir ist bekannt, dass die Unterkunft sie den Behörden melden muss, wie es das Königliche Dekret 933/2021 vorschreibt. Ich habe die ',
        acepto_enlace: 'Datenschutzerklärung',
        acepto_despues: ' gelesen.',

        menores_titulo: 'Wer mit den Kindern reist',
        menores_sub: 'Wenn ein Minderjähriger reist, müssen wir laut Gesetz wissen, in welcher Beziehung die begleitende erwachsene Person zu ihm steht.',
        menor_sin_adulto: 'Muss mit einer volljährigen Person reisen. Fügen Sie sie oben hinzu.',
        con_quien: 'Mit wem reist die Person?',
        rel_etiqueta: 'Was ist {adulto} für {menor}?',
        esa_persona: 'Diese Person',
        elige_opcion: 'Wählen Sie eine Option…',
        falta_asignar: 'Sagen Sie uns, mit wem die Person reist.',
        falta_relacion: 'Sagen Sie uns, in welcher Beziehung diese Person zu ihr steht.',

        par_PA: 'Vater oder Mutter',
        par_AB: 'Großvater oder Großmutter',
        par_HR: 'Bruder oder Schwester',
        par_TI: 'Onkel oder Tante',
        par_TU: 'Vormund',
        par_SB: 'Neffe oder Nichte',
        par_NI: 'Enkel oder Enkelin',
        par_HJ: 'Sohn oder Tochter',
        par_BA: 'Urgroßvater oder Urgroßmutter',
        par_BN: 'Urenkel oder Urenkelin',
        par_CY: 'Ehepartner oder Ehepartnerin',
        par_CD: 'Schwager oder Schwägerin',
        par_SG: 'Schwiegervater oder Schwiegermutter',
        par_YN: 'Schwiegersohn oder Schwiegertochter',
        par_OT: 'Etwas anderes',

        pagador_titulo: 'Wer hat bezahlt?',
        pagador_sub: 'Das wird zusammen mit den übrigen Daten verlangt. Der Name der Person, die bezahlt hat, genügt.',
        pagado_yo: 'Ich habe bezahlt',
        pagado_otra: 'Eine andere Person hat bezahlt',
        como_se_llama: 'Wie heißt sie?',

        listo: 'Fertig, vielen Dank',
        terminado_antes: 'Wir haben die Daten von {personas} für die Buchung ',
        terminado_despues: '. Bei der Ankunft bringen Sie nur Ihr Ausweisdokument mit, falls es geprüft werden muss.',
        terminado_error: 'Wenn Sie sich bei etwas vertan haben, öffnen Sie denselben Link und senden Sie es noch einmal.',
        volver: 'Zur Startseite',
    },

    fr: {
        meta_titulo: 'Vos données avant l\'arrivée — Apartamentos Tío José María',
        meta_descripcion: 'Enregistrement obligatoire des voyageurs (décret royal 933/2021).',
        idioma: 'Langue',
        inicio: 'Accueil',
        persona_de: 'Personne {n} sur {total}',
        ultimo_paso: 'Dernière étape',
        cargando: 'Chargement de votre réservation…',
        un_momento: 'Un instant',
        atras: 'Retour',
        guardar: 'Enregistrer',
        repasar: 'Vérifier',
        siguiente: 'Suivant',
        guardando: 'Enregistrement…',
        enviar: 'Envoyer mes données',
        guardado_aviso: 'Enregistré sur ce téléphone. Revenez au même lien quand vous voulez et reprenez là où vous vous étiez arrêté.',

        err_enlace: 'Le lien n\'est pas valide. Vérifiez l\'e-mail de confirmation ou écrivez-nous.',
        err_no_encontrada: 'Nous ne trouvons pas cette réservation. Vérifiez le lien ou écrivez-nous.',
        err_cancelada: 'Cette réservation est annulée. Si vous pensez que c\'est une erreur, écrivez-nous.',
        err_sin_confirmar: 'Cette réservation n\'est pas encore confirmée. Terminez d\'abord le paiement.',
        err_pasada: 'Ce séjour est déjà terminé. Si vous avez besoin de quelque chose, écrivez-nous.',
        abre_sin_fecha: 'Ce formulaire ouvre une semaine avant votre arrivée. Nous vous préviendrons par e-mail.',
        abre_con_fecha: 'Ce formulaire ouvre une semaine avant votre arrivée : le {fecha}. Nous vous préviendrons par e-mail.',

        env_pronto: 'C\'est encore trop tôt. Le formulaire ouvre une semaine avant votre arrivée.',
        env_sin_confirmar: 'La réservation n\'est pas encore confirmée.',
        env_pasada: 'Cette réservation est déjà terminée.',
        env_fallo: 'Nous n\'avons pas pu l\'enregistrer. Réessayez dans un instant ou écrivez-nous.',

        personas_1: '{n} personne',
        personas_n: '{n} personnes',
        persona_n: 'Personne {n}',
        una_persona: 'une personne',
        y: 'et',
        anos: '{n} ans',

        portada_titulo: 'Vos données avant l\'arrivée',
        portada_intro: 'La loi oblige l\'hébergement à enregistrer les données de toutes les personnes qui y dorment, et c\'est à nous de vous les demander. Cela se remplit une seule fois, en quelques minutes, et à l\'arrivée il ne reste plus qu\'à se souhaiter la bienvenue.',
        tu_reserva: 'Votre réservation',
        fechas_reserva: 'Du {entrada} au {salida} · {personas}',
        ya_empezado: 'Vous aviez déjà commencé. Nous reprenons là où vous vous étiez arrêté.',
        ya_hay_todas: 'Nous avons déjà les données de {nombres} ({rellenas} sur {total}). Si quelqu\'un d\'autre vient, ajoutez ses données ici ; sinon, il n\'y a rien d\'autre à faire.',
        ya_hay_falta_1: 'Nous avons déjà les données de {nombres} ({rellenas} sur {total}). Il manque 1 personne : remplissez les vôtres.',
        ya_hay_faltan: 'Nous avons déjà les données de {nombres} ({rellenas} sur {total}). Il manque {faltan} personnes : remplissez les vôtres.',
        portada_privacidad: 'Elles ne servent qu\'à remplir cette obligation. Elles ne sont partagées avec personne d\'autre.',
        portada_medias: 'Vous pouvez vous arrêter en cours de route : ce que vous écrivez reste enregistré sur ce téléphone.',
        portada_varios: 'Vous pouvez remplir pour tout le monde depuis ce téléphone, ou chacun peut le faire depuis le sien avec ce même lien.',
        empezar: 'Commencer',

        tus_datos: 'Vos données',
        quitar: 'Retirer',
        sub_titular: 'Nous commençons par la personne qui a réservé.',
        sub_segundo_movil: 'Les vôtres. Nous avons déjà celles de la personne qui a réservé.',
        sub_acompanante: 'Les données de chaque personne qui dort ici, enfants compris.',
        quitar_ayuda: 'Si cette personne préfère remplir elle-même depuis son téléphone avec le même lien, touchez « Retirer » : rien n\'est perdu, elle remplira sa fiche elle-même.',
        nombre: 'Prénom',
        apellido1: 'Nom de famille',
        apellido2: 'Deuxième nom de famille',
        apellido2_ayuda: 'Si vous n\'en avez pas, laissez vide.',
        sexo: 'Sexe',
        sexo_H: 'Homme',
        sexo_M: 'Femme',
        sexo_X: 'Je préfère ne pas le dire',
        fecha_nac: 'Date de naissance',
        tipo_doc: 'Type de document',
        num_doc: 'Numéro du document',
        soporte: 'Numéro de support',
        soporte_ayuda: 'Sur le DNI espagnol, il se trouve au dos, en haut à droite, et commence par des lettres. Sur le NIE, au même endroit. Avec d\'autres documents, laissez vide.',
        nacionalidad: 'Nationalité',
        donde_vives: 'Votre domicile habituel',
        calle: 'Rue et numéro',
        municipio: 'Commune ou ville',
        municipio_ayuda: 'Commencez à écrire et choisissez-la dans la liste.',
        cp: 'Code postal',
        pais: 'Pays',
        localizarte: 'Comment vous joindre',
        movil: 'Téléphone portable',
        email: 'E-mail',
        aviso_menor: 'Comme il s\'agit d\'un mineur, son document n\'est pas nécessaire. À la fin, nous vous demanderons avec qui il voyage.',
        aviso_menor14: 'Comme il a moins de 14 ans, il n\'a pas à signer : c\'est vous qui donnez ses données.',
        firma: 'Votre signature',
        firma_ayuda: 'Signez avec le doigt dans le cadre. La loi exige la signature de toutes les personnes de 14 ans ou plus.',
        paises_frecuentes: 'Les plus fréquents',
        paises_todos: 'Tous les pays',

        doc_D: 'DNI espagnol',
        doc_P: 'Passeport',
        doc_N: 'NIE / carte de séjour',
        doc_E: 'Carte d\'identité d\'un autre pays',
        doc_C: 'Permis de conduire de l\'UE',
        doc_X: 'Autre document officiel',

        err_nombre: 'Indiquez le prénom',
        err_apellido1: 'Indiquez le nom de famille',
        err_sexo: 'Choisissez une option',
        err_fecha: 'Indiquez la date de naissance',
        err_fecha_futura: 'Cette date n\'est pas encore arrivée',
        err_pais: 'Choisissez le pays',
        err_calle: 'Indiquez la rue et le numéro',
        err_municipio: 'Indiquez la commune ou la ville',
        err_documento: 'Indiquez le numéro du document',
        err_soporte: 'Avec un DNI ou un NIE, ce numéro est obligatoire',
        err_apellido2: 'Avec un DNI ou un NIE, le deuxième nom de famille est obligatoire',
        err_firma: 'La signature manque',
        err_movil: 'Indiquez un téléphone de contact',

        firma_aria: 'Cadre pour signer avec le doigt',
        firma_recogida: 'Signature enregistrée',
        firma_aqui: 'Signez ici avec le doigt',
        borrar: 'Effacer',

        repaso_titulo: 'Une dernière vérification',
        repaso_sub: 'Vérifiez que toutes les personnes qui vont dormir ici sont bien là.',
        sin_nombre: 'Sans nom',
        quien_reserva: 'A réservé',
        acompanante: 'Accompagnant',
        faltan_cosas: 'Il manque des données',
        cambiar: 'Modifier',
        quitar_a: 'Retirer {nombre}',
        esta_persona: 'cette personne',
        anadir: 'Ajouter une autre personne',
        reserva_para: 'Votre réservation est pour {personas}. Si vous êtes plus nombreux, écrivez-nous avant d\'arriver.',
        incompletos_1: 'Il manque quelque chose à {n} personne. Touchez « Modifier » pour la compléter.',
        incompletos_n: 'Il manque quelque chose à {n} personnes. Touchez « Modifier » pour les compléter.',
        acepto_antes: 'Les données sont exactes et je sais que l\'hébergement doit les communiquer aux autorités, comme l\'exige le décret royal 933/2021. J\'ai lu la ',
        acepto_enlace: 'politique de confidentialité',
        acepto_despues: '.',

        menores_titulo: 'Qui accompagne les enfants',
        menores_sub: 'Quand un mineur voyage, la loi nous demande de savoir quel lien a avec lui l\'adulte qui l\'accompagne.',
        menor_sin_adulto: 'Il doit voyager avec une personne majeure. Ajoutez-la plus haut.',
        con_quien: 'Avec qui voyage-t-il ?',
        rel_etiqueta: 'Pour {menor}, {adulto} est…',
        esa_persona: 'Cette personne',
        elige_opcion: 'Choisissez une option…',
        falta_asignar: 'Dites-nous avec qui il voyage.',
        falta_relacion: 'Dites-nous quel est le lien de cette personne avec lui.',

        par_PA: 'Son père ou sa mère',
        par_AB: 'Son grand-père ou sa grand-mère',
        par_HR: 'Son frère ou sa sœur',
        par_TI: 'Son oncle ou sa tante',
        par_TU: 'Son tuteur ou sa tutrice',
        par_SB: 'Son neveu ou sa nièce',
        par_NI: 'Son petit-fils ou sa petite-fille',
        par_HJ: 'Son fils ou sa fille',
        par_BA: 'Son arrière-grand-père ou son arrière-grand-mère',
        par_BN: 'Son arrière-petit-fils ou son arrière-petite-fille',
        par_CY: 'Son conjoint ou sa conjointe',
        par_CD: 'Son beau-frère ou sa belle-sœur',
        par_SG: 'Son beau-père ou sa belle-mère',
        par_YN: 'Son gendre ou sa belle-fille',
        par_OT: 'Autre',

        pagador_titulo: 'Qui a payé ?',
        pagador_sub: 'On nous le demande avec le reste des données. Le nom de la personne qui a fait le paiement suffit.',
        pagado_yo: 'C\'est moi qui ai payé',
        pagado_otra: 'Une autre personne a payé',
        como_se_llama: 'Comment s\'appelle-t-elle ?',

        listo: 'C\'est fait, merci beaucoup',
        terminado_antes: 'Nous avons les données de {personas} pour la réservation ',
        terminado_despues: '. À l\'arrivée, apportez simplement votre document au cas où il faudrait le vérifier.',
        terminado_error: 'Si vous vous êtes trompé, revenez à ce même lien et renvoyez-le.',
        volver: 'Retour à l\'accueil',
    },
};

/**
 * Qué idioma se usa al abrir:
 *   1. `?lang=xx` en la dirección (los enlaces de WhatsApp y correo lo ponen);
 *   2. si no, el idioma del navegador, si es inglés, alemán o francés;
 *   3. si no, castellano.
 */
export function idiomaInicial(desdeUrl) {
    const pedido = String(desdeUrl || '').toLowerCase().slice(0, 2);
    if (IDIOMAS.includes(pedido)) return pedido;
    let delNavegador = '';
    try { delNavegador = String(navigator.language || '').toLowerCase().slice(0, 2); } catch { /* sin navegador */ }
    if (['en', 'de', 'fr'].includes(delNavegador)) return delNavegador;
    return 'es';
}

/**
 * Devuelve `tx(clave, vars)`: el texto en el idioma pedido con `{var}`
 * sustituidas. Si falta una clave en un idioma, sale la castellana.
 */
export function traductor(lang) {
    const dic = TEXTOS[lang] || TEXTOS.es;
    return (clave, vars) => {
        const texto = dic[clave] ?? TEXTOS.es[clave] ?? clave;
        if (!vars) return texto;
        return texto.replace(/\{(\w+)\}/g, (entero, k) => (vars[k] ?? entero));
    };
}
