-- =====================================================================
-- 0001_baseline_2026-09-10.sql
--
--   *** SNAPSHOT DOCUMENTAL — NO APLICAR ***
--
-- Este fichero NO es una migracion ejecutable. Es la fotografia del
-- esquema de PRODUCCION (proyecto Supabase nmtukksbzbnuzqsksdmw) tal y
-- como estaba el 2026-09-10, ANTES de aplicar 0002 y 0003.
--
-- Por que existe: el backend se construyo por MCP directo contra la base
-- viva y nunca hubo carpeta migrations/. Esto cierra el hueco G14/P1.0
-- del plan "sustituir MisterPlan": a partir de aqui todo cambio de
-- esquema va como migracion numerada.
--
-- No lo ejecutes contra produccion (los objetos ya existen) ni contra una
-- base vacia esperando un clon exacto: no incluye datos, ni objetos de
-- los esquemas auth/storage/realtime, ni el estado de las extensiones
-- gestionadas por Supabase.
--
-- Generado consultando el catalogo: information_schema.columns,
-- pg_constraint, pg_indexes, pg_policies, pg_proc + pg_get_functiondef,
-- pg_trigger + pg_get_triggerdef, pg_get_viewdef y cron.job.
--
-- Conteo de datos en el momento del snapshot:
--   apartments 4 · guest_bookings 3 · blocked_dates 44 · high_seasons 9
--   pricing_rules 0 · customers 2 · invoices 0 · traveler_records 0
--   profiles 2 (1 admin)
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. EXTENSIONES
-- ---------------------------------------------------------------------
-- CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- CREATE EXTENSION IF NOT EXISTS btree_gist  SCHEMA public;   -- constraint no_overlap_bookings
-- CREATE EXTENSION IF NOT EXISTS vector      SCHEMA public;   -- kb_chunks (bot RAG)
-- CREATE EXTENSION IF NOT EXISTS pg_net      SCHEMA public;   -- crons que llaman a edge functions
-- CREATE EXTENSION IF NOT EXISTS pg_cron;


-- ---------------------------------------------------------------------
-- 2. TABLAS
-- ---------------------------------------------------------------------
-- Columnas `id bigint NOT NULL` sin DEFAULT son IDENTITY:
--   GENERATED ALWAYS   : apartment_instructions, blog_posts, discount_codes,
--                        guest_bookings, local_events
--   GENERATED BY DEFAULT: apartments, documents, festival_book_entries,
--                        festival_books, guest_guides, high_seasons,
--                        hinojares_content, local_content, local_places,
--                        routes, web_config

CREATE TABLE public.access_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id bigint NOT NULL,
  apartment_id bigint NOT NULL,
  lock_provider text NOT NULL,
  lock_device_id text,
  code text,
  valid_from timestamp with time zone NOT NULL,
  valid_until timestamp with time zone NOT NULL,
  provider_ref text,
  status text NOT NULL DEFAULT 'active'::text,
  sent_to_guest_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.addons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  price_cents integer NOT NULL,
  apartment_id bigint,
  icon text,
  per text DEFAULT 'stay'::text,
  max_quantity integer DEFAULT 10,
  active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.ai_interaction_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL,
  turn_index integer NOT NULL DEFAULT 0,
  user_message text NOT NULL,
  ai_response text,
  model text NOT NULL,
  model_provider text NOT NULL DEFAULT 'bedrock-eu-central-1'::text,
  tokens_input integer,
  tokens_output integer,
  latency_ms integer,
  sources_used jsonb NOT NULL DEFAULT '[]'::jsonb,
  language text DEFAULT 'es'::text,
  request_ip_country text,
  user_agent_hash text,
  error text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.apartment_instructions (
  id bigint NOT NULL,
  apartment_id bigint,
  category text NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  icon text DEFAULT 'info'::text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.apartments (
  id bigint NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  short_description text,
  capacity_people integer,
  bed_config text,
  images jsonb DEFAULT '[]'::jsonb,
  features jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  price_low numeric DEFAULT 60,
  price_high numeric DEFAULT 70,
  registration_number text DEFAULT 'A/JA/00060'::text,
  bathrooms integer DEFAULT 1,
  amenities jsonb DEFAULT '[]'::jsonb,
  airbnb_ical_url text,
  booking_ical_url text,
  lock_provider text,
  lock_device_id text,
  damage_deposit_cents integer DEFAULT 0,
  highlight text
);

CREATE TABLE public.blocked_dates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  apartment_id bigint,
  start_date date NOT NULL,
  end_date date NOT NULL,   -- OJO: INCLUSIVA (check_availability usa end_date + 1)
  source text DEFAULT 'manual'::text,
  created_at timestamp with time zone DEFAULT now(),
  reason text
);

CREATE TABLE public.blog_posts (
  id bigint NOT NULL,
  title text NOT NULL,
  slug text NOT NULL,
  excerpt text,
  content text,
  featured_image_url text,
  author text DEFAULT 'Tio Jose Maria'::text,
  category text DEFAULT 'guia'::text,
  tags text[] DEFAULT '{}'::text[],
  published boolean DEFAULT false,
  published_at timestamp with time zone,
  seo_title text,
  seo_description text,
  reading_time_min integer DEFAULT 5,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.booking_addons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id bigint NOT NULL,
  addon_id uuid,
  name_snapshot text NOT NULL,
  unit_price_cents integer NOT NULL,
  quantity integer DEFAULT 1,
  notes text,
  fulfilled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.cleaning_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  apartment_id bigint NOT NULL,
  booking_out_id bigint,
  booking_in_id bigint,
  scheduled_date date NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  assigned_to text,
  notes text,
  photos jsonb DEFAULT '[]'::jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- client_notifications_read / client_shopping_list_checks /
-- client_weekly_manual_checks / client_weekly_plans / materials_library /
-- portal_events son herencia de otra plantilla (no las usa TJM hoy).
CREATE TABLE public.client_notifications_read (
  client_id text NOT NULL,
  notification_id text NOT NULL,
  read_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.client_shopping_list_checks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  checked_items jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.client_weekly_manual_checks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  week_key text NOT NULL,
  data jsonb NOT NULL DEFAULT '{"mealPhotosSent": false, "trainingVideosSent": false}'::jsonb,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.client_weekly_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  grid jsonb NOT NULL DEFAULT '{}'::jsonb,
  prev_grid jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.consent_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_email text NOT NULL,
  purpose text NOT NULL,
  granted boolean NOT NULL,
  source text,
  ip text,
  user_agent text,
  legal_version text,
  booking_code text,
  note text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.customer_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_email text NOT NULL,
  author text,
  body text NOT NULL,
  is_warning boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.customers (
  email text NOT NULL,
  canonical_name text,
  phone text,
  nationality text,
  preferred_language text DEFAULT 'es'::text,
  tags text[] DEFAULT '{}'::text[],
  preferences text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  marketing_consent boolean DEFAULT false,
  marketing_consent_at timestamp with time zone,
  marketing_consent_source text,
  marketing_consent_revoked_at timestamp with time zone,
  review_optout boolean DEFAULT false,
  unsubscribe_token text DEFAULT encode(gen_random_bytes(16), 'hex'::text)
);

CREATE TABLE public.discount_codes (
  id bigint NOT NULL,
  code text NOT NULL,
  discount_percent integer NOT NULL DEFAULT 10,
  profile_id uuid,
  is_used boolean DEFAULT false,
  valid_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.documents (
  id bigint NOT NULL,
  title text NOT NULL,
  file_url text NOT NULL,
  visibility text DEFAULT 'publico'::text,
  category text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.email_subscribers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  subscribed_at timestamp with time zone DEFAULT now(),
  source text DEFAULT 'guia_section'::text,
  is_active boolean DEFAULT true,
  guide_sent_at timestamp with time zone
);

CREATE TABLE public.festival_book_entries (
  id bigint NOT NULL,
  book_id bigint NOT NULL,
  entry_type text NOT NULL,
  title text NOT NULL,
  content text,
  image_url text,
  images jsonb DEFAULT '[]'::jsonb,
  event_date date,
  start_time time without time zone,
  end_time time without time zone,
  location text,
  extra_data jsonb DEFAULT '{}'::jsonb,
  order_index integer DEFAULT 0,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.festival_books (
  id bigint NOT NULL,
  year integer NOT NULL,
  title text NOT NULL,
  subtitle text,
  cover_image_url text,
  intro_text text,
  start_date date,
  end_date date,
  is_published boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- TABLA CENTRAL DE RESERVAS (se llama guest_bookings, NO bookings)
CREATE TABLE public.guest_bookings (
  id bigint NOT NULL,                 -- GENERATED ALWAYS AS IDENTITY
  apartment_id bigint,
  guest_name text NOT NULL,
  guest_email text NOT NULL,
  guest_phone text,
  guest_address text,
  pax_count integer DEFAULT 2,
  check_in date NOT NULL,
  check_out date NOT NULL,
  nights integer GENERATED ALWAYS AS (check_out - check_in) STORED,  -- OJO: generada, no se escribe a mano
  total_price numeric,
  price_breakdown jsonb,
  status text DEFAULT 'pending'::text,
  notes text,
  source text DEFAULT 'web'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  profile_id uuid,
  review_request_sent_at timestamp with time zone,
  expires_at timestamp with time zone,
  payment_intent_id text,
  payment_status text DEFAULT 'pending'::text,
  payment_amount_paid numeric DEFAULT 0,
  booking_code text,
  confirmation_email_sent_at timestamp with time zone,
  reminder_7d_email_sent_at timestamp with time zone,
  reminder_24h_email_sent_at timestamp with time zone,
  arrival_email_sent_at timestamp with time zone,
  departure_email_sent_at timestamp with time zone,
  review_request_email_sent_at timestamp with time zone,
  reactivation_email_sent_at timestamp with time zone,
  operator_notified_at timestamp with time zone,
  damage_deposit_intent_id text,
  damage_deposit_status text DEFAULT 'none'::text,
  damage_deposit_amount_cents integer DEFAULT 0,
  damage_deposit_notes text
);

CREATE TABLE public.guest_guides (
  id bigint NOT NULL,
  category text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  image_url text,
  video_url text,
  location_url text,
  difficulty text,
  duration text
);

CREATE TABLE public.guidebooks (
  apartment_id bigint NOT NULL,
  welcome_message text,
  wifi_name text,
  wifi_password text,
  checkin_instructions text,
  house_rules text,
  appliance_instructions text,
  nearby_recommendations text,
  parking_info text,
  emergency_contact text,
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.high_seasons (
  id bigint NOT NULL,
  name text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.hinojares_content (
  id bigint NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  content text,
  emoji text,
  order_index integer NOT NULL DEFAULT 0,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.inbox_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source text NOT NULL,
  from_name text,
  from_email text,
  from_phone text,
  subject text,
  body text NOT NULL,
  classification text,
  urgency text,
  sentiment text,
  language text,
  suggested_response text,
  status text DEFAULT 'new'::text,
  booking_code text,
  assigned_to text,
  internal_notes text,
  triaged_at timestamp with time zone,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.internal_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  file_url text NOT NULL,
  file_size bigint,
  mime_type text,
  category text DEFAULT 'general'::text,
  tags text[],
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  uploaded_by uuid
);

CREATE TABLE public.internal_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  category text NOT NULL DEFAULT 'general'::text,
  scheduled_date date NOT NULL,
  recurrence text DEFAULT 'none'::text,
  status text DEFAULT 'pending'::text,
  assigned_to text,
  priority text DEFAULT 'normal'::text,
  last_completed_at timestamp with time zone,
  completion_notes text,
  auto_reschedule boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id bigint,
  serie text NOT NULL DEFAULT 'A'::text,
  numero bigint NOT NULL,
  fecha_emision date NOT NULL DEFAULT CURRENT_DATE,
  tipo text NOT NULL DEFAULT 'completa'::text,
  rectifica_invoice_id uuid,
  motivo_rectificacion text,
  emisor_nif text NOT NULL DEFAULT '26433801Q'::text,
  emisor_nombre text NOT NULL DEFAULT 'Jesús Martínez Sánchez'::text,
  emisor_direccion text NOT NULL DEFAULT 'Calle Baja 1, 23486 Hinojares, Jaén, España'::text,
  receptor_nif text,
  receptor_nombre text,
  receptor_direccion text,
  receptor_email text,
  concepto text NOT NULL,
  base_imponible numeric(10,2) NOT NULL,
  tipo_iva numeric(5,2) NOT NULL DEFAULT 10.00,
  cuota_iva numeric(10,2) NOT NULL,
  total numeric(10,2) NOT NULL,
  moneda text NOT NULL DEFAULT 'EUR'::text,
  verifactu_hash text,
  verifactu_hash_previo text,
  verifactu_sent_at timestamp with time zone,
  verifactu_response jsonb,
  verifactu_status text DEFAULT 'pending'::text,
  pdf_url text,
  email_sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.kb_chunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_type text NOT NULL,
  source_id text,
  title text NOT NULL,
  content text NOT NULL,
  content_hash text NOT NULL,
  embedding vector(1024),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  language text NOT NULL DEFAULT 'es'::text,
  token_count integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.local_content (
  id bigint NOT NULL,
  category text NOT NULL,
  slug text NOT NULL,
  title text NOT NULL,
  subtitle text,
  content text,
  excerpt text,
  image_url text,
  images jsonb DEFAULT '[]'::jsonb,
  meta_title text,
  meta_description text,
  extra_data jsonb DEFAULT '{}'::jsonb,
  order_index integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.local_events (
  id bigint NOT NULL,
  title text NOT NULL,
  description text,
  event_date date,
  end_date date,
  season text,
  category text,
  image_url text,
  location text,
  is_recurring boolean DEFAULT false,
  active boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  slug text,
  meta_title text,
  meta_description text,
  time_text text,
  organizer text,
  program jsonb DEFAULT '[]'::jsonb,
  source_url text,
  verified_at timestamp with time zone
);

CREATE TABLE public.local_places (
  id bigint NOT NULL,
  type text,
  name text NOT NULL,
  description text,
  location_url text,
  web_url text,
  image_url text,
  updated_at timestamp with time zone DEFAULT now(),
  phone text,
  address text,
  category text DEFAULT 'general'::text,
  slug text,
  excerpt text,
  meta_title text,
  meta_description text,
  is_featured boolean DEFAULT false,
  order_index integer DEFAULT 0,
  images jsonb DEFAULT '[]'::jsonb
);

CREATE TABLE public.materials_library (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_by uuid,
  title text NOT NULL,
  description text,
  type text NOT NULL,
  url text NOT NULL,
  category text DEFAULT 'general'::text,
  tags text[],
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.otp_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  code_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used boolean DEFAULT false,
  used_at timestamp with time zone,
  requested_ip text,
  requested_ua text,
  attempts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.owner_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  period_year integer NOT NULL,
  period_month integer NOT NULL,
  sent_at timestamp with time zone,
  sent_to text,
  bookings_count integer,
  nights_count integer,
  revenue_cents bigint,
  addons_revenue_cents bigint DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.portal_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  event_date date NOT NULL,
  event_time time without time zone,
  end_time time without time zone,
  category text NOT NULL DEFAULT 'general'::text,
  category_color text,
  location text,
  url text,
  speaker text,
  image_url text,
  is_visible boolean DEFAULT true,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.pricing_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  apartment_id bigint,
  name text NOT NULL,
  rule_type text NOT NULL,
  multiplier numeric(5,3),
  flat_extra numeric(10,2),
  threshold_days integer,
  weekday_mask text,
  occupancy_threshold numeric(3,2),
  valid_from date,
  valid_until date,
  active boolean NOT NULL DEFAULT true,
  priority integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  role text DEFAULT 'cliente'::text,
  full_name text,
  updated_at timestamp with time zone DEFAULT now(),
  email text,
  access_mode text DEFAULT 'always'::text,
  is_active boolean DEFAULT true,
  is_profile_completed boolean DEFAULT false,
  phone text,
  address text,
  pax_count integer DEFAULT 1,
  check_in date,
  check_out date,
  notes text,
  preferences text
);

CREATE TABLE public.protocols (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL,
  category text NOT NULL,
  title text NOT NULL,
  summary text,
  content text NOT NULL,
  related_tab text,
  keywords text[],
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid
);

CREATE TABLE public.rate_limits (
  id bigint NOT NULL DEFAULT nextval('rate_limits_id_seq'::regclass),
  key text NOT NULL,
  window_start timestamp with time zone NOT NULL,
  count integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  author text NOT NULL,
  content text NOT NULL,
  rating integer,
  source text DEFAULT 'Booking.com'::text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  avatar_url text,
  profile_id uuid,
  status text DEFAULT 'approved'::text
);

CREATE TABLE public.routes (
  id bigint NOT NULL,
  title text NOT NULL,
  description text,
  difficulty text,
  duration text,
  map_url text,
  image_url text,
  updated_at timestamp with time zone DEFAULT now(),
  distance_km numeric,
  elevation_gain integer,
  start_lat double precision,
  start_lon double precision,
  coordinates jsonb,
  gpx_url text,
  category text DEFAULT 'senderismo'::text,
  highlights text[],
  route_group text DEFAULT 'walk'::text,
  images jsonb DEFAULT '[]'::jsonb,
  slug text,
  excerpt text,
  meta_title text,
  meta_description text,
  is_featured boolean DEFAULT false,
  image_credit text
);

-- DATOS PERSONALES DEL PARTE DE VIAJEROS (RD 933/2021). Solo service_role
-- y admin pueden leerla. Retencion 3 anos (cron prune-traveler-records).
CREATE TABLE public.traveler_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id bigint NOT NULL,
  is_titular boolean NOT NULL DEFAULT false,
  apellido_primero text NOT NULL,
  apellido_segundo text,
  nombre text NOT NULL,
  sexo text NOT NULL,
  tipo_documento text NOT NULL,
  numero_documento text NOT NULL,
  soporte_documento text,
  nacionalidad text NOT NULL,
  fecha_nacimiento date NOT NULL,
  direccion_via text NOT NULL,
  direccion_municipio text NOT NULL,
  direccion_cp text NOT NULL,
  direccion_pais text NOT NULL,
  telefono_fijo text,
  telefono_movil text,
  email text,
  parentesco text,
  firma_base64 text,
  submitted_at timestamp with time zone,
  mir_reference text,
  mir_response_status text,
  mir_response_payload jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  ip_origen_hash text,
  user_agent_hash text,
  consent_privacy_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.web_config (
  id bigint NOT NULL,
  section text NOT NULL,
  key text NOT NULL,
  value text NOT NULL,
  updated_at timestamp with time zone DEFAULT now()
);


-- ---------------------------------------------------------------------
-- 3. CONSTRAINTS (PK / UNIQUE / FK / CHECK / EXCLUDE)
-- ---------------------------------------------------------------------

ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_pkey PRIMARY KEY (id);
ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_lock_provider_check CHECK ((lock_provider = ANY (ARRAY['ttlock'::text, 'nuki'::text, 'manual'::text])));
ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_status_check CHECK ((status = ANY (ARRAY['pending_provision'::text, 'active'::text, 'expired'::text, 'revoked'::text, 'error'::text])));
ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_apartment_id_fkey FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE;
ALTER TABLE public.access_codes ADD CONSTRAINT access_codes_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES guest_bookings(id) ON DELETE CASCADE;

ALTER TABLE public.addons ADD CONSTRAINT addons_pkey PRIMARY KEY (id);
ALTER TABLE public.addons ADD CONSTRAINT addons_apartment_id_fkey FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE;

ALTER TABLE public.ai_interaction_logs ADD CONSTRAINT ai_interaction_logs_pkey PRIMARY KEY (id);

ALTER TABLE public.apartment_instructions ADD CONSTRAINT apartment_instructions_pkey PRIMARY KEY (id);
ALTER TABLE public.apartment_instructions ADD CONSTRAINT apartment_instructions_category_check CHECK ((category = ANY (ARRAY['llegada'::text, 'apartamento'::text, 'wifi'::text, 'chimenea'::text, 'cocina'::text, 'calefaccion'::text, 'limpieza'::text, 'salida'::text, 'otro'::text])));
ALTER TABLE public.apartment_instructions ADD CONSTRAINT apartment_instructions_apartment_id_fkey FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE;

ALTER TABLE public.apartments ADD CONSTRAINT apartments_pkey PRIMARY KEY (id);
ALTER TABLE public.apartments ADD CONSTRAINT apartments_name_key UNIQUE (name);
ALTER TABLE public.apartments ADD CONSTRAINT apartments_slug_key UNIQUE (slug);
ALTER TABLE public.apartments ADD CONSTRAINT apartments_lock_provider_check CHECK (((lock_provider = ANY (ARRAY['ttlock'::text, 'nuki'::text, 'manual'::text])) OR (lock_provider IS NULL)));

ALTER TABLE public.blocked_dates ADD CONSTRAINT blocked_dates_pkey PRIMARY KEY (id);
ALTER TABLE public.blocked_dates ADD CONSTRAINT blocked_dates_apartment_id_fkey FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE;

ALTER TABLE public.blog_posts ADD CONSTRAINT blog_posts_pkey PRIMARY KEY (id);
ALTER TABLE public.blog_posts ADD CONSTRAINT blog_posts_slug_key UNIQUE (slug);
ALTER TABLE public.blog_posts ADD CONSTRAINT blog_posts_category_check CHECK ((category = ANY (ARRAY['guia'::text, 'pueblo'::text, 'naturaleza'::text, 'gastronomia'::text, 'practico'::text])));

ALTER TABLE public.booking_addons ADD CONSTRAINT booking_addons_pkey PRIMARY KEY (id);
ALTER TABLE public.booking_addons ADD CONSTRAINT booking_addons_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES addons(id) ON DELETE SET NULL;
ALTER TABLE public.booking_addons ADD CONSTRAINT booking_addons_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES guest_bookings(id) ON DELETE CASCADE;

ALTER TABLE public.cleaning_tasks ADD CONSTRAINT cleaning_tasks_pkey PRIMARY KEY (id);
ALTER TABLE public.cleaning_tasks ADD CONSTRAINT cleaning_tasks_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'done'::text, 'skipped'::text, 'issue'::text])));
ALTER TABLE public.cleaning_tasks ADD CONSTRAINT cleaning_tasks_apartment_id_fkey FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE;
ALTER TABLE public.cleaning_tasks ADD CONSTRAINT cleaning_tasks_booking_in_id_fkey FOREIGN KEY (booking_in_id) REFERENCES guest_bookings(id) ON DELETE SET NULL;
ALTER TABLE public.cleaning_tasks ADD CONSTRAINT cleaning_tasks_booking_out_id_fkey FOREIGN KEY (booking_out_id) REFERENCES guest_bookings(id) ON DELETE SET NULL;

ALTER TABLE public.client_notifications_read ADD CONSTRAINT client_notifications_read_pkey PRIMARY KEY (client_id, notification_id);

ALTER TABLE public.client_shopping_list_checks ADD CONSTRAINT client_shopping_list_checks_pkey PRIMARY KEY (id);
ALTER TABLE public.client_shopping_list_checks ADD CONSTRAINT client_shopping_list_checks_client_id_plan_id_key UNIQUE (client_id, plan_id);
ALTER TABLE public.client_shopping_list_checks ADD CONSTRAINT client_shopping_list_checks_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;

ALTER TABLE public.client_weekly_manual_checks ADD CONSTRAINT client_weekly_manual_checks_pkey PRIMARY KEY (id);
ALTER TABLE public.client_weekly_manual_checks ADD CONSTRAINT client_weekly_manual_checks_client_id_week_key_key UNIQUE (client_id, week_key);
ALTER TABLE public.client_weekly_manual_checks ADD CONSTRAINT client_weekly_manual_checks_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;

ALTER TABLE public.client_weekly_plans ADD CONSTRAINT client_weekly_plans_pkey PRIMARY KEY (id);
ALTER TABLE public.client_weekly_plans ADD CONSTRAINT client_weekly_plans_client_id_plan_id_key UNIQUE (client_id, plan_id);
ALTER TABLE public.client_weekly_plans ADD CONSTRAINT client_weekly_plans_client_id_fkey FOREIGN KEY (client_id) REFERENCES profiles(id) ON DELETE CASCADE;

ALTER TABLE public.consent_log ADD CONSTRAINT consent_log_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_notes ADD CONSTRAINT customer_notes_pkey PRIMARY KEY (id);
ALTER TABLE public.customers ADD CONSTRAINT customers_pkey PRIMARY KEY (email);
ALTER TABLE public.customers ADD CONSTRAINT customers_unsubscribe_token_key UNIQUE (unsubscribe_token);

ALTER TABLE public.discount_codes ADD CONSTRAINT discount_codes_pkey PRIMARY KEY (id);
ALTER TABLE public.discount_codes ADD CONSTRAINT discount_codes_code_key UNIQUE (code);
ALTER TABLE public.discount_codes ADD CONSTRAINT discount_codes_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES auth.users(id);

ALTER TABLE public.documents ADD CONSTRAINT documents_pkey PRIMARY KEY (id);
ALTER TABLE public.documents ADD CONSTRAINT documents_visibility_check CHECK ((visibility = ANY (ARRAY['publico'::text, 'solo_clientes'::text])));

ALTER TABLE public.email_subscribers ADD CONSTRAINT email_subscribers_pkey PRIMARY KEY (id);
ALTER TABLE public.email_subscribers ADD CONSTRAINT email_subscribers_email_key UNIQUE (email);

ALTER TABLE public.festival_book_entries ADD CONSTRAINT festival_book_entries_pkey PRIMARY KEY (id);
ALTER TABLE public.festival_book_entries ADD CONSTRAINT festival_book_entries_entry_type_check CHECK ((entry_type = ANY (ARRAY['programa'::text, 'articulo'::text, 'patrocinador'::text, 'dedicatoria'::text, 'galeria'::text])));
ALTER TABLE public.festival_book_entries ADD CONSTRAINT festival_book_entries_book_id_fkey FOREIGN KEY (book_id) REFERENCES festival_books(id) ON DELETE CASCADE;

ALTER TABLE public.festival_books ADD CONSTRAINT festival_books_pkey PRIMARY KEY (id);
ALTER TABLE public.festival_books ADD CONSTRAINT festival_books_year_key UNIQUE (year);

ALTER TABLE public.guest_bookings ADD CONSTRAINT guest_bookings_pkey PRIMARY KEY (id);
ALTER TABLE public.guest_bookings ADD CONSTRAINT guest_bookings_booking_code_key UNIQUE (booking_code);
ALTER TABLE public.guest_bookings ADD CONSTRAINT guest_bookings_payment_status_check CHECK ((payment_status = ANY (ARRAY['pending'::text, 'partial'::text, 'paid'::text, 'refunded'::text, 'failed'::text])));
ALTER TABLE public.guest_bookings ADD CONSTRAINT guest_bookings_status_check CHECK ((status = ANY (ARRAY['hold'::text, 'pending'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text, 'expired'::text])));
ALTER TABLE public.guest_bookings ADD CONSTRAINT guest_bookings_apartment_id_fkey FOREIGN KEY (apartment_id) REFERENCES apartments(id);
ALTER TABLE public.guest_bookings ADD CONSTRAINT guest_bookings_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE SET NULL;
-- Barrera anti-overbooking a nivel de motor (requiere btree_gist):
ALTER TABLE public.guest_bookings ADD CONSTRAINT no_overlap_bookings
  EXCLUDE USING gist (apartment_id WITH =, daterange(check_in, check_out, '[)'::text) WITH &&)
  WHERE ((status = ANY (ARRAY['hold'::text, 'pending'::text, 'confirmed'::text])));

ALTER TABLE public.guest_guides ADD CONSTRAINT guest_guides_pkey PRIMARY KEY (id);

ALTER TABLE public.guidebooks ADD CONSTRAINT guidebooks_pkey PRIMARY KEY (apartment_id);
ALTER TABLE public.guidebooks ADD CONSTRAINT guidebooks_apartment_id_fkey FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE;

ALTER TABLE public.high_seasons ADD CONSTRAINT high_seasons_pkey PRIMARY KEY (id);

ALTER TABLE public.hinojares_content ADD CONSTRAINT hinojares_content_pkey PRIMARY KEY (id);
ALTER TABLE public.hinojares_content ADD CONSTRAINT hinojares_content_type_check CHECK ((type = ANY (ARRAY['stat'::text, 'history'::text, 'tradition'::text, 'gastronomy'::text])));

ALTER TABLE public.inbox_messages ADD CONSTRAINT inbox_messages_pkey PRIMARY KEY (id);

ALTER TABLE public.internal_documents ADD CONSTRAINT internal_documents_pkey PRIMARY KEY (id);
ALTER TABLE public.internal_documents ADD CONSTRAINT internal_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id);

ALTER TABLE public.internal_tasks ADD CONSTRAINT internal_tasks_pkey PRIMARY KEY (id);

ALTER TABLE public.invoices ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);
ALTER TABLE public.invoices ADD CONSTRAINT invoices_tipo_check CHECK ((tipo = ANY (ARRAY['completa'::text, 'simplificada'::text, 'rectificativa'::text])));
ALTER TABLE public.invoices ADD CONSTRAINT invoices_verifactu_status_check CHECK ((verifactu_status = ANY (ARRAY['pending'::text, 'stub'::text, 'sent'::text, 'error'::text, 'retry'::text])));
ALTER TABLE public.invoices ADD CONSTRAINT invoices_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES guest_bookings(id) ON DELETE RESTRICT;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_rectifica_invoice_id_fkey FOREIGN KEY (rectifica_invoice_id) REFERENCES invoices(id);

ALTER TABLE public.kb_chunks ADD CONSTRAINT kb_chunks_pkey PRIMARY KEY (id);
ALTER TABLE public.kb_chunks ADD CONSTRAINT kb_chunks_source_type_check CHECK ((source_type = ANY (ARRAY['apartment'::text, 'route'::text, 'event'::text, 'place'::text, 'faq'::text, 'guide'::text, 'blog_post'::text, 'hinojares_content'::text, 'how_to'::text, 'custom'::text])));

ALTER TABLE public.local_content ADD CONSTRAINT local_content_pkey PRIMARY KEY (id);
ALTER TABLE public.local_content ADD CONSTRAINT local_content_slug_key UNIQUE (slug);
ALTER TABLE public.local_content ADD CONSTRAINT local_content_category_check CHECK ((category = ANY (ARRAY['pueblo'::text, 'cultura'::text, 'gastronomia'::text, 'naturaleza'::text, 'servicios'::text, 'fiestas'::text, 'como_llegar'::text])));

ALTER TABLE public.local_events ADD CONSTRAINT local_events_pkey PRIMARY KEY (id);

ALTER TABLE public.local_places ADD CONSTRAINT local_places_pkey PRIMARY KEY (id);
ALTER TABLE public.local_places ADD CONSTRAINT local_places_type_check CHECK ((type = ANY (ARRAY['restaurante'::text, 'turismo_activo'::text, 'servicio'::text, 'emergencia'::text, 'supermercado'::text, 'banco'::text, 'farmacia'::text, 'gasolinera'::text, 'patrimonio'::text, 'naturaleza'::text, 'otro'::text])));

ALTER TABLE public.materials_library ADD CONSTRAINT materials_library_pkey PRIMARY KEY (id);
ALTER TABLE public.materials_library ADD CONSTRAINT materials_library_type_check CHECK ((type = ANY (ARRAY['link'::text, 'document'::text, 'video'::text, 'audio'::text])));

ALTER TABLE public.otp_codes ADD CONSTRAINT otp_codes_pkey PRIMARY KEY (id);

ALTER TABLE public.owner_reports ADD CONSTRAINT owner_reports_pkey PRIMARY KEY (id);
ALTER TABLE public.owner_reports ADD CONSTRAINT owner_reports_period_year_period_month_key UNIQUE (period_year, period_month);

ALTER TABLE public.portal_events ADD CONSTRAINT portal_events_pkey PRIMARY KEY (id);

ALTER TABLE public.pricing_rules ADD CONSTRAINT pricing_rules_pkey PRIMARY KEY (id);
ALTER TABLE public.pricing_rules ADD CONSTRAINT pricing_rules_rule_type_check CHECK ((rule_type = ANY (ARRAY['weekend_premium'::text, 'last_minute'::text, 'early_bird'::text, 'min_nights'::text, 'occupancy_boost'::text])));
ALTER TABLE public.pricing_rules ADD CONSTRAINT pricing_rules_apartment_id_fkey FOREIGN KEY (apartment_id) REFERENCES apartments(id) ON DELETE CASCADE;

ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_email_key UNIQUE (email);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'cliente'::text])));

ALTER TABLE public.protocols ADD CONSTRAINT protocols_pkey PRIMARY KEY (id);
ALTER TABLE public.protocols ADD CONSTRAINT protocols_slug_key UNIQUE (slug);
ALTER TABLE public.protocols ADD CONSTRAINT protocols_category_check CHECK ((category = ANY (ARRAY['help'::text, 'process'::text, 'reference'::text])));
ALTER TABLE public.protocols ADD CONSTRAINT protocols_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id);

ALTER TABLE public.rate_limits ADD CONSTRAINT rate_limits_pkey PRIMARY KEY (id);

ALTER TABLE public.reviews ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);
ALTER TABLE public.reviews ADD CONSTRAINT reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)));
ALTER TABLE public.reviews ADD CONSTRAINT reviews_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id);

ALTER TABLE public.routes ADD CONSTRAINT routes_pkey PRIMARY KEY (id);

ALTER TABLE public.traveler_records ADD CONSTRAINT traveler_records_pkey PRIMARY KEY (id);
ALTER TABLE public.traveler_records ADD CONSTRAINT traveler_records_parentesco_check CHECK (((parentesco = ANY (ARRAY['PA'::text, 'TU'::text, 'AB'::text, 'OT'::text])) OR (parentesco IS NULL)));
ALTER TABLE public.traveler_records ADD CONSTRAINT traveler_records_sexo_check CHECK ((sexo = ANY (ARRAY['H'::text, 'M'::text, 'X'::text])));
ALTER TABLE public.traveler_records ADD CONSTRAINT traveler_records_tipo_documento_check CHECK ((tipo_documento = ANY (ARRAY['D'::text, 'P'::text, 'C'::text, 'I'::text, 'N'::text, 'E'::text, 'X'::text])));
ALTER TABLE public.traveler_records ADD CONSTRAINT traveler_records_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES guest_bookings(id) ON DELETE RESTRICT;

ALTER TABLE public.web_config ADD CONSTRAINT web_config_pkey PRIMARY KEY (id);
ALTER TABLE public.web_config ADD CONSTRAINT web_config_key_key UNIQUE (key);


-- ---------------------------------------------------------------------
-- 4. INDICES (los que no vienen de una constraint)
-- ---------------------------------------------------------------------
CREATE INDEX access_codes_booking_idx ON public.access_codes USING btree (booking_id);
CREATE INDEX access_codes_valid_idx ON public.access_codes USING btree (valid_from, valid_until, status);
CREATE INDEX ai_logs_created_at_idx ON public.ai_interaction_logs USING btree (created_at DESC);
CREATE INDEX ai_logs_session_idx ON public.ai_interaction_logs USING btree (session_id, turn_index);
CREATE INDEX blocked_dates_apartment_dates_idx ON public.blocked_dates USING btree (apartment_id, start_date, end_date);
CREATE INDEX idx_blog_posts_category ON public.blog_posts USING btree (category);
CREATE INDEX idx_blog_posts_published ON public.blog_posts USING btree (published, published_at DESC);
CREATE INDEX idx_blog_posts_slug ON public.blog_posts USING btree (slug);
CREATE INDEX booking_addons_booking_idx ON public.booking_addons USING btree (booking_id);
CREATE INDEX cleaning_tasks_apartment_idx ON public.cleaning_tasks USING btree (apartment_id, scheduled_date);
CREATE INDEX cleaning_tasks_date_idx ON public.cleaning_tasks USING btree (scheduled_date, status);
CREATE INDEX idx_client_notif_read_client ON public.client_notifications_read USING btree (client_id);
CREATE INDEX consent_log_email_idx ON public.consent_log USING btree (customer_email, created_at DESC);
CREATE INDEX customer_notes_email_idx ON public.customer_notes USING btree (customer_email, created_at DESC);
CREATE INDEX customers_tags_idx ON public.customers USING gin (tags);
CREATE INDEX idx_festival_book_entries_book_id ON public.festival_book_entries USING btree (book_id);
CREATE INDEX idx_festival_book_entries_type ON public.festival_book_entries USING btree (entry_type);
CREATE INDEX guest_bookings_apartment_status_idx ON public.guest_bookings USING btree (apartment_id, status) WHERE (status = ANY (ARRAY['hold'::text, 'pending'::text, 'confirmed'::text]));
CREATE INDEX guest_bookings_profile_id_idx ON public.guest_bookings USING btree (profile_id);
CREATE INDEX guest_bookings_review_request_idx ON public.guest_bookings USING btree (check_out, review_request_sent_at, status) WHERE ((status = 'confirmed'::text) AND (review_request_sent_at IS NULL));
CREATE INDEX inbox_status_idx ON public.inbox_messages USING btree (status, created_at DESC);
CREATE INDEX inbox_urgency_idx ON public.inbox_messages USING btree (urgency) WHERE (status <> 'archived'::text);
CREATE INDEX internal_docs_category_idx ON public.internal_documents USING btree (category, uploaded_at DESC);
CREATE INDEX internal_tasks_date_idx ON public.internal_tasks USING btree (scheduled_date);
CREATE INDEX internal_tasks_status_idx ON public.internal_tasks USING btree (status);
CREATE INDEX invoices_booking_idx ON public.invoices USING btree (booking_id);
CREATE INDEX invoices_emision_idx ON public.invoices USING btree (fecha_emision DESC);
CREATE UNIQUE INDEX invoices_serie_numero_idx ON public.invoices USING btree (serie, numero);
CREATE INDEX invoices_verifactu_idx ON public.invoices USING btree (verifactu_status, verifactu_sent_at);
CREATE UNIQUE INDEX kb_chunks_dedupe_idx ON public.kb_chunks USING btree (source_type, COALESCE(source_id, ''::text), content_hash);
CREATE INDEX kb_chunks_embedding_hnsw_idx ON public.kb_chunks USING hnsw (embedding vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX kb_chunks_lang_idx ON public.kb_chunks USING btree (language);
CREATE INDEX kb_chunks_source_idx ON public.kb_chunks USING btree (source_type, source_id);
CREATE INDEX idx_local_content_category ON public.local_content USING btree (category);
CREATE INDEX idx_local_content_slug ON public.local_content USING btree (slug);
CREATE INDEX idx_materials_library_active ON public.materials_library USING btree (is_active);
CREATE INDEX idx_materials_library_category ON public.materials_library USING btree (category);
CREATE INDEX idx_materials_library_type ON public.materials_library USING btree (type);
CREATE INDEX otp_codes_email_idx ON public.otp_codes USING btree (lower(email), expires_at DESC);
CREATE INDEX idx_portal_events_date ON public.portal_events USING btree (event_date);
CREATE INDEX idx_portal_events_visible ON public.portal_events USING btree (is_visible) WHERE (is_visible = true);
CREATE INDEX pricing_rules_active_idx ON public.pricing_rules USING btree (active, priority DESC);
CREATE INDEX protocols_category_idx ON public.protocols USING btree (category, sort_order);
CREATE INDEX protocols_related_tab_idx ON public.protocols USING btree (related_tab) WHERE (related_tab IS NOT NULL);
CREATE UNIQUE INDEX rate_limits_key_window_idx ON public.rate_limits USING btree (key, window_start);
CREATE INDEX traveler_records_booking_idx ON public.traveler_records USING btree (booking_id);
CREATE INDEX traveler_records_submitted_idx ON public.traveler_records USING btree (submitted_at, mir_response_status);


-- ---------------------------------------------------------------------
-- 5. FUNCIONES
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.check_availability(p_check_in date, p_check_out date, p_pax integer DEFAULT 1)
 RETURNS TABLE(apartment_id bigint, slug text, name text, capacity_people integer, nights integer, nightly_avg numeric, total_price numeric, price_breakdown jsonb, images jsonb, short_description text)
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
    v_nights int;
    v_advance int;
    v_today date := current_date;
BEGIN
    IF p_check_in IS NULL OR p_check_out IS NULL OR p_check_out <= p_check_in THEN
        RAISE EXCEPTION 'invalid_dates' USING ERRCODE = '22023';
    END IF;
    IF p_check_in < v_today THEN
        RAISE EXCEPTION 'check_in_in_past' USING ERRCODE = '22023';
    END IF;

    v_nights := p_check_out - p_check_in;
    v_advance := p_check_in - v_today;

    RETURN QUERY
    WITH candidate_apartments AS (
        SELECT a.id, a.slug, a.name, a.capacity_people, a.price_low, a.price_high,
               a.images, a.short_description
        FROM public.apartments a
        WHERE a.is_active = true
          AND a.capacity_people >= p_pax
    ),
    -- min_nights: descartar apartamentos donde la estancia es menor que la regla aplicable
    min_nights_violations AS (
        SELECT DISTINCT ca.id AS apt_id
        FROM candidate_apartments ca
        JOIN public.pricing_rules pr ON pr.active = true
            AND pr.rule_type = 'min_nights'
            AND (pr.apartment_id IS NULL OR pr.apartment_id = ca.id)
            AND (pr.valid_from IS NULL OR pr.valid_from <= p_check_in)
            AND (pr.valid_until IS NULL OR pr.valid_until >= p_check_out)
        WHERE v_nights < COALESCE(pr.threshold_days, 1)
    ),
    daily_prices AS (
        SELECT
            ca.id AS apt_id,
            ca.slug, ca.name, ca.capacity_people,
            ca.images, ca.short_description,
            d::date AS night_date,
            -- Precio base segun high_seasons
            (CASE
                WHEN EXISTS (
                    SELECT 1 FROM public.high_seasons hs
                    WHERE d::date >= hs.start_date AND d::date <= hs.end_date
                ) THEN ca.price_high
                ELSE ca.price_low
            END) AS base_price
        FROM candidate_apartments ca
        CROSS JOIN generate_series(p_check_in, p_check_out - interval '1 day', interval '1 day') AS d
        WHERE ca.id NOT IN (SELECT apt_id FROM min_nights_violations)
    ),
    priced_nights AS (
        SELECT
            dp.*,
            -- Aplicar weekend_premium (multiplier o flat_extra) si la noche cae en weekday_mask
            (dp.base_price
                + COALESCE((
                    SELECT COALESCE(pr.flat_extra, 0)
                            + dp.base_price * (COALESCE(pr.multiplier, 1) - 1)
                    FROM public.pricing_rules pr
                    WHERE pr.active = true
                      AND pr.rule_type = 'weekend_premium'
                      AND (pr.apartment_id IS NULL OR pr.apartment_id = dp.apt_id)
                      AND (pr.valid_from IS NULL OR pr.valid_from <= dp.night_date)
                      AND (pr.valid_until IS NULL OR pr.valid_until >= dp.night_date)
                      AND (pr.weekday_mask IS NULL OR pr.weekday_mask ILIKE
                           '%' || (ARRAY['SUN','MON','TUE','WED','THU','FRI','SAT'])[EXTRACT(DOW FROM dp.night_date)::int + 1] || '%')
                    ORDER BY pr.priority DESC NULLS LAST
                    LIMIT 1
                ), 0)
            ) AS night_price
        FROM daily_prices dp
    ),
    aggregated AS (
        SELECT
            pn.apt_id,
            MAX(pn.slug) AS slug,
            MAX(pn.name) AS name,
            MAX(pn.capacity_people) AS capacity_people,
            (MAX(pn.images::text))::jsonb AS images,
            MAX(pn.short_description) AS short_description,
            v_nights AS nights,
            ROUND(AVG(pn.night_price), 2) AS nightly_avg,
            SUM(pn.night_price) AS subtotal,
            jsonb_build_object(
                'nights', v_nights,
                'breakdown', jsonb_agg(jsonb_build_object(
                    'date', pn.night_date,
                    'base', pn.base_price,
                    'price', pn.night_price
                ) ORDER BY pn.night_date)
            ) AS price_breakdown
        FROM priced_nights pn
        GROUP BY pn.apt_id
    ),
    -- last_minute / early_bird sobre el total
    with_global_rules AS (
        SELECT
            ag.*,
            (ag.subtotal * COALESCE((
                SELECT COALESCE(pr.multiplier, 1)
                FROM public.pricing_rules pr
                WHERE pr.active = true
                  AND pr.rule_type IN ('last_minute', 'early_bird')
                  AND (pr.apartment_id IS NULL OR pr.apartment_id = ag.apt_id)
                  AND (pr.valid_from IS NULL OR pr.valid_from <= p_check_in)
                  AND (pr.valid_until IS NULL OR pr.valid_until >= p_check_out)
                  AND (
                    (pr.rule_type = 'last_minute' AND v_advance <= COALESCE(pr.threshold_days, 0))
                    OR
                    (pr.rule_type = 'early_bird' AND v_advance >= COALESCE(pr.threshold_days, 999))
                  )
                ORDER BY pr.priority DESC NULLS LAST
                LIMIT 1
            ), 1)) AS total_with_rules
        FROM aggregated ag
    )
    SELECT
        a.apt_id, a.slug, a.name, a.capacity_people, a.nights,
        ROUND((a.total_with_rules / a.nights), 2) AS nightly_avg,
        ROUND(a.total_with_rules, 2) AS total_price,
        a.price_breakdown, a.images, a.short_description
    FROM with_global_rules a
    WHERE NOT EXISTS (
        SELECT 1 FROM public.guest_bookings gb
        WHERE gb.apartment_id = a.apt_id
          AND gb.status IN ('hold', 'pending', 'confirmed')
          AND daterange(gb.check_in, gb.check_out, '[)') && daterange(p_check_in, p_check_out, '[)')
    )
    AND NOT EXISTS (
        SELECT 1 FROM public.blocked_dates bd
        WHERE bd.apartment_id = a.apt_id
          AND daterange(bd.start_date, bd.end_date + 1, '[)') && daterange(p_check_in, p_check_out, '[)')
    )
    ORDER BY total_price ASC;
END $function$;

CREATE OR REPLACE FUNCTION public.check_is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
    SELECT EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role = 'admin'
    );
$function$;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$function$;

-- OJO: en el snapshot is_staff() arrastra la lista de roles de OTRO proyecto
-- (Cuid-Arte). Ninguno de esos roles existe aqui: profiles_role_check solo
-- admite 'admin' y 'cliente', asi que hoy is_staff() == es admin.
-- 0003_rol_staff.sql lo corrige a ('admin','staff').
CREATE OR REPLACE FUNCTION public.is_staff()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT COALESCE(
    (SELECT role IN ('admin', 'head_coach', 'coach', 'closer', 'contabilidad', 'endocrino', 'psicologo', 'rrss', 'direccion', 'setter')
     FROM public.profiles WHERE id = auth.uid()),
    false
  );
$function$;

CREATE OR REPLACE FUNCTION public.get_auth_role()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.generate_booking_code()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN 'TJM-' || upper(substring(encode(gen_random_bytes(4), 'hex') from 1 for 6));
END $function$;

CREATE OR REPLACE FUNCTION public.create_booking_hold(p_apartment_id bigint, p_check_in date, p_check_out date, p_pax integer, p_guest_name text, p_guest_email text, p_guest_phone text DEFAULT NULL::text)
 RETURNS TABLE(booking_id bigint, booking_code text, total_price numeric, expires_at timestamp with time zone)
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_total numeric;
    v_breakdown jsonb;
    v_code text;
    v_expires timestamptz := now() + interval '15 minutes';
    v_id bigint;
BEGIN
    SELECT ca.total_price, ca.price_breakdown INTO v_total, v_breakdown
    FROM public.check_availability(p_check_in, p_check_out, p_pax) ca
    WHERE ca.apartment_id = p_apartment_id
    LIMIT 1;

    IF v_total IS NULL THEN
        RAISE EXCEPTION 'apartment_not_available' USING ERRCODE = '22023';
    END IF;

    LOOP
        v_code := public.generate_booking_code();
        EXIT WHEN NOT EXISTS (SELECT 1 FROM public.guest_bookings gb WHERE gb.booking_code = v_code);
    END LOOP;

    INSERT INTO public.guest_bookings (
        apartment_id, guest_name, guest_email, guest_phone,
        pax_count, check_in, check_out, total_price, price_breakdown,
        status, expires_at, booking_code, source
    ) VALUES (
        p_apartment_id, p_guest_name, p_guest_email, p_guest_phone,
        p_pax, p_check_in, p_check_out, v_total, v_breakdown,
        'hold', v_expires, v_code, 'web'
    )
    RETURNING id INTO v_id;

    RETURN QUERY SELECT v_id, v_code, v_total, v_expires;
END $function$;

CREATE OR REPLACE FUNCTION public.expire_booking_holds()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    expired_count int;
BEGIN
    UPDATE public.guest_bookings
    SET status = 'expired', updated_at = now()
    WHERE status = 'hold' AND expires_at < now();
    GET DIAGNOSTICS expired_count = ROW_COUNT;
    RETURN expired_count;
END $function$;

CREATE OR REPLACE FUNCTION public.ensure_customer_exists()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    IF NEW.guest_email IS NOT NULL AND NEW.guest_email <> '' THEN
        INSERT INTO public.customers (email, canonical_name, phone)
        VALUES (LOWER(TRIM(NEW.guest_email)), NEW.guest_name, NEW.guest_phone)
        ON CONFLICT (email) DO UPDATE SET
            canonical_name = COALESCE(public.customers.canonical_name, EXCLUDED.canonical_name),
            phone = COALESCE(EXCLUDED.phone, public.customers.phone),
            updated_at = now();
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.schedule_cleaning_on_booking_confirmed()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.status = 'confirmed' AND (OLD IS NULL OR OLD.status != 'confirmed') THEN
        INSERT INTO public.cleaning_tasks (apartment_id, booking_out_id, scheduled_date, status)
        SELECT NEW.apartment_id, NEW.id, NEW.check_out, 'pending'
        WHERE NOT EXISTS (
            SELECT 1 FROM public.cleaning_tasks
            WHERE apartment_id = NEW.apartment_id AND scheduled_date = NEW.check_out
        );
    END IF;
    RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public.issue_invoice(p_booking_id bigint, p_receptor_nif text DEFAULT NULL::text, p_receptor_nombre text DEFAULT NULL::text, p_receptor_direccion text DEFAULT NULL::text, p_receptor_email text DEFAULT NULL::text)
 RETURNS TABLE(invoice_id uuid, serie text, numero bigint, total numeric)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_existing_id uuid;
    v_existing_serie text;
    v_existing_numero bigint;
    v_existing_total numeric;
    v_year int := EXTRACT(YEAR FROM current_date)::int;
    v_serie text := 'A' || v_year::text;
    v_numero bigint;
    v_booking record;
    v_concepto text;
    v_total numeric;
    v_base numeric;
    v_cuota numeric;
    v_tipo_iva numeric := 10.00;
    v_hash_previo text;
    v_invoice_id uuid;
BEGIN
    -- Idempotencia
    SELECT id, serie, numero, total
    INTO v_existing_id, v_existing_serie, v_existing_numero, v_existing_total
    FROM public.invoices
    WHERE booking_id = p_booking_id AND tipo != 'rectificativa'
    LIMIT 1;
    IF v_existing_id IS NOT NULL THEN
        RETURN QUERY SELECT v_existing_id, v_existing_serie, v_existing_numero, v_existing_total;
        RETURN;
    END IF;

    -- Cargar booking
    SELECT gb.id, gb.booking_code, gb.check_in, gb.check_out, gb.total_price,
           gb.guest_name, gb.guest_email, gb.pax_count, a.name AS apt_name
    INTO v_booking
    FROM public.guest_bookings gb
    JOIN public.apartments a ON a.id = gb.apartment_id
    WHERE gb.id = p_booking_id;

    IF v_booking IS NULL THEN
        RAISE EXCEPTION 'booking_not_found' USING ERRCODE = '22023';
    END IF;

    v_concepto := format('Estancia en %s del %s al %s (%s noches, %s personas)',
        v_booking.apt_name, v_booking.check_in, v_booking.check_out,
        (v_booking.check_out - v_booking.check_in), v_booking.pax_count);

    v_total := v_booking.total_price;
    v_base := ROUND(v_total / (1 + v_tipo_iva / 100), 2);
    v_cuota := v_total - v_base;

    -- Numeracion correlativa por serie del ano
    SELECT COALESCE(MAX(numero), 0) + 1 INTO v_numero
    FROM public.invoices WHERE serie = v_serie;

    -- Hash previo (cadena Verifactu)
    SELECT verifactu_hash INTO v_hash_previo
    FROM public.invoices
    WHERE serie = v_serie AND numero = v_numero - 1;

    INSERT INTO public.invoices (
        booking_id, serie, numero, fecha_emision, tipo,
        receptor_nif, receptor_nombre, receptor_direccion, receptor_email,
        concepto, base_imponible, tipo_iva, cuota_iva, total, moneda,
        verifactu_hash_previo
    ) VALUES (
        p_booking_id, v_serie, v_numero, current_date,
        CASE WHEN p_receptor_nif IS NULL THEN 'simplificada' ELSE 'completa' END,
        p_receptor_nif,
        COALESCE(p_receptor_nombre, v_booking.guest_name),
        p_receptor_direccion,
        COALESCE(p_receptor_email, v_booking.guest_email),
        v_concepto, v_base, v_tipo_iva, v_cuota, v_total, 'EUR',
        v_hash_previo
    ) RETURNING id INTO v_invoice_id;

    -- Generar verifactu_hash con los campos clave (SHA256 hex)
    UPDATE public.invoices SET verifactu_hash = encode(
        digest(
            COALESCE(verifactu_hash_previo, '') || '|' ||
            emisor_nif || '|' || serie || '|' || numero::text || '|' ||
            fecha_emision::text || '|' || total::text || '|' || cuota_iva::text,
            'sha256'
        ), 'hex')
    WHERE id = v_invoice_id;

    RETURN QUERY SELECT v_invoice_id, v_serie, v_numero, v_total;
END $function$;

CREATE OR REPLACE FUNCTION public.submit_traveler_records(p_booking_code text, p_travelers jsonb)
 RETURNS TABLE(saved integer, booking_id bigint)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_booking_id bigint;
    v_check_in date;
    v_check_out date;
    v_status text;
    v_count int := 0;
    v_traveler jsonb;
BEGIN
    -- Validar booking
    SELECT id, check_in, check_out, status
    INTO v_booking_id, v_check_in, v_check_out, v_status
    FROM public.guest_bookings
    WHERE booking_code = upper(p_booking_code);

    IF v_booking_id IS NULL THEN
        RAISE EXCEPTION 'booking_not_found' USING ERRCODE = '22023';
    END IF;
    IF v_status NOT IN ('confirmed', 'completed') THEN
        RAISE EXCEPTION 'booking_status_invalid: %', v_status USING ERRCODE = '22023';
    END IF;
    IF v_check_in - current_date > 7 THEN
        RAISE EXCEPTION 'precheckin_too_early' USING ERRCODE = '22023';
    END IF;
    IF v_check_out < current_date THEN
        RAISE EXCEPTION 'booking_already_past' USING ERRCODE = '22023';
    END IF;
    IF jsonb_array_length(p_travelers) = 0 OR jsonb_array_length(p_travelers) > 20 THEN
        RAISE EXCEPTION 'invalid_traveler_count' USING ERRCODE = '22023';
    END IF;

    DELETE FROM public.traveler_records WHERE traveler_records.booking_id = v_booking_id AND submitted_at IS NULL;

    FOR v_traveler IN SELECT * FROM jsonb_array_elements(p_travelers) LOOP
        INSERT INTO public.traveler_records (
            booking_id, is_titular,
            apellido_primero, apellido_segundo, nombre, sexo,
            tipo_documento, numero_documento, soporte_documento,
            nacionalidad, fecha_nacimiento,
            direccion_via, direccion_municipio, direccion_cp, direccion_pais,
            telefono_fijo, telefono_movil, email,
            parentesco, firma_base64
        ) VALUES (
            v_booking_id,
            COALESCE((v_traveler->>'is_titular')::boolean, false),
            v_traveler->>'apellido_primero',
            v_traveler->>'apellido_segundo',
            v_traveler->>'nombre',
            v_traveler->>'sexo',
            v_traveler->>'tipo_documento',
            v_traveler->>'numero_documento',
            v_traveler->>'soporte_documento',
            v_traveler->>'nacionalidad',
            (v_traveler->>'fecha_nacimiento')::date,
            v_traveler->>'direccion_via',
            v_traveler->>'direccion_municipio',
            v_traveler->>'direccion_cp',
            v_traveler->>'direccion_pais',
            v_traveler->>'telefono_fijo',
            v_traveler->>'telefono_movil',
            v_traveler->>'email',
            v_traveler->>'parentesco',
            v_traveler->>'firma_base64'
        );
        v_count := v_count + 1;
    END LOOP;

    RETURN QUERY SELECT v_count, v_booking_id;
END $function$;

CREATE OR REPLACE FUNCTION public.record_marketing_consent(p_email text, p_granted boolean, p_source text DEFAULT 'admin_panel'::text, p_ip text DEFAULT NULL::text, p_user_agent text DEFAULT NULL::text, p_legal_version text DEFAULT '1.0'::text, p_booking_code text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    log_id UUID;
    norm_email TEXT := LOWER(TRIM(p_email));
BEGIN
    INSERT INTO public.customers (email)
    VALUES (norm_email) ON CONFLICT (email) DO NOTHING;

    IF p_granted THEN
        UPDATE public.customers SET
            marketing_consent = true,
            marketing_consent_at = now(),
            marketing_consent_source = p_source,
            marketing_consent_revoked_at = NULL,
            updated_at = now()
        WHERE email = norm_email;
    ELSE
        UPDATE public.customers SET
            marketing_consent = false,
            marketing_consent_revoked_at = now(),
            updated_at = now()
        WHERE email = norm_email;
    END IF;

    INSERT INTO public.consent_log (customer_email, purpose, granted, source, ip, user_agent, legal_version, booking_code)
    VALUES (norm_email, 'marketing', p_granted, p_source, p_ip, p_user_agent, p_legal_version, p_booking_code)
    RETURNING id INTO log_id;

    RETURN log_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.search_kb_chunks(query_embedding vector, match_threshold double precision DEFAULT 0.25, match_count integer DEFAULT 6, lang text DEFAULT 'es'::text)
 RETURNS TABLE(id uuid, title text, content text, source_type text, metadata jsonb, similarity double precision)
 LANGUAGE plpgsql
 STABLE
AS $function$
BEGIN
    RETURN QUERY
    SELECT kc.id, kc.title, kc.content, kc.source_type, kc.metadata,
        1 - (kc.embedding <=> query_embedding) AS similarity
    FROM public.kb_chunks kc
    WHERE kc.embedding IS NOT NULL
      AND (lang IS NULL OR kc.language = lang)
      AND 1 - (kc.embedding <=> query_embedding) > match_threshold
    ORDER BY kc.embedding <=> query_embedding
    LIMIT match_count;
END $function$;

CREATE OR REPLACE FUNCTION public.cleanup_expired_otps()
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
    DELETE FROM public.otp_codes WHERE expires_at < now() - interval '24 hours';
$function$;

CREATE OR REPLACE FUNCTION public.cleanup_old_rate_limits()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  DELETE FROM rate_limits WHERE window_start < now() - interval '24 hours';
END;
$function$;

CREATE OR REPLACE FUNCTION public.prune_ai_interaction_logs()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    deleted_count int;
BEGIN
    DELETE FROM public.ai_interaction_logs
    WHERE created_at < now() - interval '12 months' - interval '7 days';
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END $function$;

CREATE OR REPLACE FUNCTION public.prune_traveler_records()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    deleted_count int;
BEGIN
    -- 3 anos + 30 dias desde el check_out del booking asociado
    DELETE FROM public.traveler_records tr
    WHERE EXISTS (
        SELECT 1 FROM public.guest_bookings gb
        WHERE gb.id = tr.booking_id
          AND gb.check_out < current_date - interval '3 years' - interval '30 days'
    );
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END $function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public.update_materials_library_timestamp()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;


-- ---------------------------------------------------------------------
-- 6. TRIGGERS
-- ---------------------------------------------------------------------
CREATE TRIGGER cleaning_tasks_set_updated_at BEFORE UPDATE ON public.cleaning_tasks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER guest_bookings_ensure_customer AFTER INSERT OR UPDATE ON public.guest_bookings FOR EACH ROW EXECUTE FUNCTION ensure_customer_exists();
CREATE TRIGGER guest_bookings_schedule_cleaning AFTER UPDATE OF status ON public.guest_bookings FOR EACH ROW EXECUTE FUNCTION schedule_cleaning_on_booking_confirmed();
CREATE TRIGGER invoices_set_updated_at BEFORE UPDATE ON public.invoices FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER kb_chunks_set_updated_at BEFORE UPDATE ON public.kb_chunks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER materials_library_updated BEFORE UPDATE ON public.materials_library FOR EACH ROW EXECUTE FUNCTION update_materials_library_timestamp();
CREATE TRIGGER pricing_rules_set_updated_at BEFORE UPDATE ON public.pricing_rules FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER protocols_set_updated_at BEFORE UPDATE ON public.protocols FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER traveler_records_set_updated_at BEFORE UPDATE ON public.traveler_records FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ---------------------------------------------------------------------
-- 7. VISTAS (todas con security_invoker = true)
-- ---------------------------------------------------------------------

CREATE OR REPLACE VIEW public.bookings_email_queue WITH (security_invoker=true) AS
 SELECT b.id, b.booking_code, b.guest_name, b.guest_email, b.check_in, b.check_out,
    b.total_price, b.apartment_id, a.name AS apartment_name, a.slug AS apartment_slug,
    b.status, b.payment_status,
        CASE
            WHEN b.status = 'confirmed'::text AND b.confirmation_email_sent_at IS NULL THEN 'confirmation'::text
            WHEN (b.check_in - CURRENT_DATE) = 7 AND b.reminder_7d_email_sent_at IS NULL THEN 'reminder_7d'::text
            WHEN (b.check_in - CURRENT_DATE) = 1 AND b.reminder_24h_email_sent_at IS NULL THEN 'reminder_24h'::text
            WHEN b.check_in = CURRENT_DATE AND b.arrival_email_sent_at IS NULL THEN 'arrival'::text
            WHEN b.check_out = CURRENT_DATE AND b.departure_email_sent_at IS NULL THEN 'departure'::text
            WHEN (CURRENT_DATE - b.check_out) = 1 AND b.review_request_email_sent_at IS NULL THEN 'review_request'::text
            WHEN (CURRENT_DATE - b.check_out) = 30 AND b.reactivation_email_sent_at IS NULL THEN 'reactivation'::text
            ELSE NULL::text
        END AS pending_email
   FROM guest_bookings b
     JOIN apartments a ON a.id = b.apartment_id
  WHERE (b.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AND b.guest_email IS NOT NULL;

CREATE OR REPLACE VIEW public.v_admin_kpis WITH (security_invoker=true) AS
 SELECT ( SELECT round(100.0 * sum(LEAST(gb.check_out, CURRENT_DATE + 30) - GREATEST(gb.check_in, CURRENT_DATE))::numeric / NULLIF(30 * (( SELECT count(*) AS count
                   FROM apartments
                  WHERE apartments.is_active = true)), 0)::numeric, 1) AS round
           FROM guest_bookings gb
          WHERE (gb.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AND gb.check_in < (CURRENT_DATE + 30) AND gb.check_out > CURRENT_DATE) AS ocupacion_30d_pct,
    ( SELECT COALESCE(sum(guest_bookings.total_price), 0::numeric)
           FROM guest_bookings
          WHERE (guest_bookings.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AND guest_bookings.check_in >= (CURRENT_DATE - '30 days'::interval) AND guest_bookings.check_in < CURRENT_DATE) AS ingresos_30d,
    ( SELECT COALESCE(sum(guest_bookings.total_price), 0::numeric)
           FROM guest_bookings
          WHERE (guest_bookings.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AND guest_bookings.check_in >= CURRENT_DATE AND guest_bookings.check_in < (CURRENT_DATE + 30)) AS ingresos_proximos_30d,
    ( SELECT count(*) FROM guest_bookings
          WHERE (guest_bookings.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AND guest_bookings.check_out >= CURRENT_DATE) AS reservas_activas,
    ( SELECT count(*) FROM guest_bookings
          WHERE (guest_bookings.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AND guest_bookings.check_in = CURRENT_DATE) AS checkins_hoy,
    ( SELECT count(*) FROM guest_bookings
          WHERE (guest_bookings.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AND guest_bookings.check_out = CURRENT_DATE) AS checkouts_hoy,
    ( SELECT count(*) FROM guest_bookings
          WHERE (guest_bookings.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AND guest_bookings.check_in > CURRENT_DATE AND guest_bookings.check_in <= (CURRENT_DATE + 7)) AS llegadas_7d,
    ( SELECT count(*) FROM guest_bookings
          WHERE guest_bookings.status = 'hold'::text AND guest_bookings.expires_at IS NOT NULL AND guest_bookings.expires_at < (now() + '00:30:00'::interval) AND guest_bookings.expires_at > now()) AS holds_expirando,
    ( SELECT count(*) FROM traveler_records tr JOIN guest_bookings gb ON gb.id = tr.booking_id
          WHERE tr.submitted_at IS NULL AND gb.check_in <= CURRENT_DATE AND (gb.status = ANY (ARRAY['confirmed'::text, 'completed'::text]))) AS ses_pendientes,
    ( SELECT count(*) FROM traveler_records WHERE traveler_records.mir_response_status = 'retry'::text) AS ses_errores,
    ( SELECT count(*) FROM guest_bookings gb
          WHERE gb.status = 'confirmed'::text AND gb.check_in = (CURRENT_DATE + 1) AND NOT (EXISTS ( SELECT 1 FROM traveler_records tr WHERE tr.booking_id = gb.id))) AS precheckin_pendiente_24h,
    ( SELECT count(*) FROM cleaning_tasks
          WHERE cleaning_tasks.status = 'pending'::text AND cleaning_tasks.scheduled_date <= (CURRENT_DATE + 1)) AS limpiezas_pendientes,
    ( SELECT count(*) FROM invoices
          WHERE invoices.verifactu_status = ANY (ARRAY['stub'::text, 'error'::text, 'retry'::text])) AS facturas_verifactu_pendientes,
    ( SELECT count(DISTINCT ai_interaction_logs.session_id) FROM ai_interaction_logs
          WHERE ai_interaction_logs.created_at > (now() - '24:00:00'::interval)) AS bot_sesiones_24h,
    ( SELECT count(*) FROM ai_interaction_logs
          WHERE ai_interaction_logs.error IS NOT NULL AND ai_interaction_logs.created_at > (now() - '7 days'::interval)) AS bot_errores_7d;

CREATE OR REPLACE VIEW public.v_admin_revenue_monthly WITH (security_invoker=true) AS
 SELECT to_char(date_trunc('month'::text, check_in::timestamp with time zone), 'YYYY-MM'::text) AS month,
    count(*) AS bookings,
    sum(check_out - check_in) AS nights,
    sum(total_price) AS revenue,
    round(avg(total_price), 2) AS avg_booking
   FROM guest_bookings
  WHERE (status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AND check_in >= date_trunc('month'::text, CURRENT_DATE - '11 mons'::interval)
  GROUP BY 1
  ORDER BY 1 DESC;

CREATE OR REPLACE VIEW public.v_admin_upcoming WITH (security_invoker=true) AS
 SELECT gb.id, gb.booking_code, gb.guest_name, gb.guest_email, gb.guest_phone,
    gb.check_in, gb.check_out, gb.pax_count, gb.total_price, gb.payment_status,
    gb.status, gb.apartment_id, a.name AS apartment_name, a.slug AS apartment_slug,
        CASE
            WHEN gb.check_in >= CURRENT_DATE AND gb.check_in <= (CURRENT_DATE + 14) THEN 'llegada'::text
            WHEN gb.check_out >= CURRENT_DATE AND gb.check_out <= (CURRENT_DATE + 14) THEN 'salida'::text
            ELSE NULL::text
        END AS event_type,
        CASE
            WHEN gb.check_in >= CURRENT_DATE AND gb.check_in <= (CURRENT_DATE + 14) THEN gb.check_in
            WHEN gb.check_out >= CURRENT_DATE AND gb.check_out <= (CURRENT_DATE + 14) THEN gb.check_out
            ELSE NULL::date
        END AS event_date,
    gb.confirmation_email_sent_at IS NOT NULL AS confirmation_sent,
    (EXISTS ( SELECT 1 FROM traveler_records tr WHERE tr.booking_id = gb.id)) AS precheckin_done,
    ( SELECT count(*) FROM traveler_records tr WHERE tr.booking_id = gb.id) AS traveler_count,
    (EXISTS ( SELECT 1 FROM access_codes ac WHERE ac.booking_id = gb.id AND (ac.status = ANY (ARRAY['active'::text, 'pending_provision'::text])))) AS has_access_code
   FROM guest_bookings gb
     JOIN apartments a ON a.id = gb.apartment_id
  WHERE (gb.status = ANY (ARRAY['confirmed'::text, 'completed'::text]))
    AND (gb.check_in >= CURRENT_DATE AND gb.check_in <= (CURRENT_DATE + 14) OR gb.check_out >= CURRENT_DATE AND gb.check_out <= (CURRENT_DATE + 14));

CREATE OR REPLACE VIEW public.v_customers_360 WITH (security_invoker=true) AS
 WITH base AS (
         SELECT lower(TRIM(BOTH FROM gb.guest_email)) AS email,
            max(gb.guest_name) AS last_name_from_bookings,
            max(gb.guest_phone) AS last_phone_from_bookings,
            count(*) FILTER (WHERE gb.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AS total_stays,
            count(*) FILTER (WHERE gb.status = 'cancelled'::text) AS total_cancelled,
            COALESCE(sum(gb.total_price) FILTER (WHERE gb.status = ANY (ARRAY['confirmed'::text, 'completed'::text])), 0::numeric) AS lifetime_value,
            min(gb.check_in) FILTER (WHERE gb.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AS first_stay,
            max(gb.check_out) FILTER (WHERE gb.status = ANY (ARRAY['confirmed'::text, 'completed'::text])) AS last_stay,
            COALESCE(sum(gb.check_out - gb.check_in) FILTER (WHERE gb.status = ANY (ARRAY['confirmed'::text, 'completed'::text])), 0::bigint) AS total_nights
           FROM guest_bookings gb
          WHERE gb.guest_email IS NOT NULL AND gb.guest_email <> ''::text
          GROUP BY 1
        )
 SELECT b.email,
    COALESCE(c.canonical_name, b.last_name_from_bookings) AS last_name,
    COALESCE(c.phone, b.last_phone_from_bookings) AS last_phone,
    c.tags, c.preferences, c.preferred_language, c.nationality,
    b.total_stays, b.total_cancelled, b.lifetime_value,
    b.first_stay, b.last_stay, b.total_nights,
    fav.name AS favorite_apartment,
    note.body AS last_note, note.is_warning AS last_note_is_warning, note.created_at AS last_note_at,
    nc.notes_count, nc.warnings_count, r.avg_rating
   FROM base b
     LEFT JOIN customers c ON c.email = b.email
     LEFT JOIN LATERAL ( SELECT a.name FROM guest_bookings gb2 JOIN apartments a ON a.id = gb2.apartment_id
          WHERE lower(TRIM(BOTH FROM gb2.guest_email)) = b.email AND (gb2.status = ANY (ARRAY['confirmed'::text, 'completed'::text]))
          GROUP BY a.name ORDER BY (count(*)) DESC LIMIT 1) fav ON true
     LEFT JOIN LATERAL ( SELECT cn.body, cn.is_warning, cn.created_at FROM customer_notes cn
          WHERE cn.customer_email = b.email ORDER BY cn.created_at DESC LIMIT 1) note ON true
     LEFT JOIN LATERAL ( SELECT count(*) AS notes_count, count(*) FILTER (WHERE customer_notes.is_warning) AS warnings_count
           FROM customer_notes WHERE customer_notes.customer_email = b.email) nc ON true
     LEFT JOIN LATERAL ( SELECT round(avg(rv.rating), 1) AS avg_rating FROM reviews rv JOIN profiles p ON p.id = rv.profile_id
          WHERE lower(TRIM(BOTH FROM p.email)) = b.email) r ON true;


-- ---------------------------------------------------------------------
-- 8. RLS
-- ---------------------------------------------------------------------
-- RLS activada en TODAS las tablas de public. otp_codes y rate_limits la
-- tienen activada SIN politicas (deliberado: solo service_role las toca).

ALTER TABLE public.access_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_interaction_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.apartment_instructions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.apartments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cleaning_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_notifications_read ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_shopping_list_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_weekly_manual_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_weekly_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consent_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discount_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.festival_book_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.festival_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_guides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guidebooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.high_seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hinojares_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbox_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kb_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.local_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.local_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.local_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials_library ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otp_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owner_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portal_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.protocols ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.traveler_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.web_config ENABLE ROW LEVEL SECURITY;

-- --- politicas (todas PERMISSIVE) ---
CREATE POLICY access_codes_service_all ON public.access_codes FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY admin_read_access_codes ON public.access_codes FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

CREATE POLICY admin_all_addons ON public.addons FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());
CREATE POLICY public_addons_read ON public.addons FOR SELECT TO anon USING (active = true);

CREATE POLICY admin_read_ai_interaction_logs ON public.ai_interaction_logs FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY ai_logs_service_all ON public.ai_interaction_logs FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Admin gestiona instrucciones" ON public.apartment_instructions FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Clientes autenticados leen instrucciones" ON public.apartment_instructions FOR SELECT TO authenticated USING (true);

CREATE POLICY "Admins gestionan apartamentos" ON public.apartments FOR ALL USING (check_is_admin());
CREATE POLICY "Apartamentos públicos" ON public.apartments FOR SELECT USING (true);

CREATE POLICY "Admins gestionan bloqueos" ON public.blocked_dates FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Fechas bloqueadas públicas" ON public.blocked_dates FOR SELECT USING (true);

CREATE POLICY "Admin CRUD completo en blog" ON public.blog_posts FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Lectura publica de posts publicados" ON public.blog_posts FOR SELECT USING (published = true);

CREATE POLICY admin_all_booking_addons ON public.booking_addons FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());

CREATE POLICY admin_read_cleaning_tasks ON public.cleaning_tasks FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY cleaning_tasks_service_all ON public.cleaning_tasks FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY clients_delete_own_notif_reads ON public.client_notifications_read FOR DELETE USING (true);
CREATE POLICY clients_insert_own_notif_reads ON public.client_notifications_read FOR INSERT WITH CHECK (true);
CREATE POLICY clients_read_own_notif_reads ON public.client_notifications_read FOR SELECT USING (true);

CREATE POLICY "Clients can insert their own shopping checks" ON public.client_shopping_list_checks FOR INSERT WITH CHECK (auth.uid() = client_id);
CREATE POLICY "Clients can update their own shopping checks" ON public.client_shopping_list_checks FOR UPDATE USING (auth.uid() = client_id);
CREATE POLICY "Clients can view their own shopping checks" ON public.client_shopping_list_checks FOR SELECT USING (auth.uid() = client_id);
CREATE POLICY "Staff can insert all shopping checks" ON public.client_shopping_list_checks FOR INSERT TO authenticated WITH CHECK (is_staff());
CREATE POLICY "Staff can update all shopping checks" ON public.client_shopping_list_checks FOR UPDATE TO authenticated USING (is_staff()) WITH CHECK (is_staff());
CREATE POLICY "Staff can view all shopping checks" ON public.client_shopping_list_checks FOR SELECT TO authenticated USING (is_staff());

CREATE POLICY "Clients can insert their own weekly manual checks" ON public.client_weekly_manual_checks FOR INSERT WITH CHECK (auth.uid() = client_id);
CREATE POLICY "Clients can update their own weekly manual checks" ON public.client_weekly_manual_checks FOR UPDATE USING (auth.uid() = client_id);
CREATE POLICY "Clients can view their own weekly manual checks" ON public.client_weekly_manual_checks FOR SELECT USING (auth.uid() = client_id);

CREATE POLICY "Clients can insert their own weekly plans" ON public.client_weekly_plans FOR INSERT WITH CHECK (auth.uid() = client_id);
CREATE POLICY "Clients can update their own weekly plans" ON public.client_weekly_plans FOR UPDATE USING (auth.uid() = client_id);
CREATE POLICY "Clients can view their own weekly plans" ON public.client_weekly_plans FOR SELECT USING (auth.uid() = client_id);
CREATE POLICY "Staff can insert all weekly plans" ON public.client_weekly_plans FOR INSERT TO authenticated WITH CHECK (is_staff());
CREATE POLICY "Staff can update all weekly plans" ON public.client_weekly_plans FOR UPDATE TO authenticated USING (is_staff()) WITH CHECK (is_staff());
CREATE POLICY "Staff can view all weekly plans" ON public.client_weekly_plans FOR SELECT TO authenticated USING (is_staff());

CREATE POLICY admin_read_consent_log ON public.consent_log FOR SELECT TO authenticated USING (check_is_admin());
CREATE POLICY admin_write_consent_log ON public.consent_log FOR INSERT TO authenticated WITH CHECK (check_is_admin());

CREATE POLICY admin_all_customer_notes ON public.customer_notes FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());
CREATE POLICY admin_all_customers ON public.customers FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());

CREATE POLICY "Admin gestiona codigos" ON public.discount_codes FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Cliente ve sus propios codigos" ON public.discount_codes FOR SELECT TO authenticated USING (profile_id = auth.uid());

CREATE POLICY "Admins gestionan documentos" ON public.documents FOR ALL USING (check_is_admin());
CREATE POLICY "Documentos para clientes" ON public.documents FOR SELECT TO authenticated USING ((visibility = ANY (ARRAY['publico'::text, 'solo_clientes'::text])) OR is_admin());
CREATE POLICY "Documentos publicos" ON public.documents FOR SELECT USING (visibility = 'publico');

CREATE POLICY "Admin reads subscribers" ON public.email_subscribers FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Anyone can subscribe" ON public.email_subscribers FOR INSERT WITH CHECK (true);

CREATE POLICY "Admin write festival_book_entries" ON public.festival_book_entries FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Public read festival_book_entries" ON public.festival_book_entries FOR SELECT USING (true);
CREATE POLICY "Admin write festival_books" ON public.festival_books FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Public read festival_books" ON public.festival_books FOR SELECT USING (true);

CREATE POLICY "Admin full access" ON public.guest_bookings FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Public create pending or hold booking" ON public.guest_bookings FOR INSERT TO anon, authenticated WITH CHECK (
  (status = ANY (ARRAY['pending'::text, 'hold'::text])) AND (payment_status = 'pending'::text)
  AND (guest_name IS NOT NULL) AND ((length(btrim(guest_name)) >= 2) AND (length(btrim(guest_name)) <= 120))
  AND (guest_email IS NOT NULL) AND (POSITION(('@'::text) IN (guest_email)) > 1)
  AND (check_in >= CURRENT_DATE) AND (check_out > check_in) AND ((check_out - check_in) <= 30)
  AND ((pax_count >= 1) AND (pax_count <= 10))
  AND (total_price IS NOT NULL) AND (total_price >= (0)::numeric) AND (total_price <= (10000)::numeric));
CREATE POLICY "Users read own bookings" ON public.guest_bookings FOR SELECT USING ((guest_email = (auth.jwt() ->> 'email')) OR (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')));

CREATE POLICY "Admins gestionan guías" ON public.guest_guides FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Permitir lectura pública de guías" ON public.guest_guides FOR SELECT USING (true);

CREATE POLICY admin_all_guidebooks ON public.guidebooks FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());
CREATE POLICY public_guidebooks_read ON public.guidebooks FOR SELECT TO anon USING (true);

CREATE POLICY "Admins gestionan temporadas" ON public.high_seasons FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Permitir lectura pública de temporadas" ON public.high_seasons FOR SELECT USING (true);

CREATE POLICY "Admin write hinojares_content" ON public.hinojares_content FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Public read hinojares_content" ON public.hinojares_content FOR SELECT USING (true);

CREATE POLICY admin_all_inbox ON public.inbox_messages FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());
CREATE POLICY anon_insert_inbox ON public.inbox_messages FOR INSERT TO anon WITH CHECK (source = ANY (ARRAY['web_form'::text, 'bot'::text]));

CREATE POLICY internal_docs_admin_all ON public.internal_documents FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());
CREATE POLICY internal_docs_service_all ON public.internal_documents FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY admin_all_internal_tasks ON public.internal_tasks FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());

CREATE POLICY admin_read_invoices ON public.invoices FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY clients_read_own_invoices ON public.invoices FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM guest_bookings gb WHERE gb.id = invoices.booking_id AND lower(gb.guest_email) = lower(auth.jwt() ->> 'email')));
CREATE POLICY invoices_service_all ON public.invoices FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY kb_chunks_public_read ON public.kb_chunks FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY kb_chunks_service_write ON public.kb_chunks FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Admin write local_content" ON public.local_content FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Public read local_content" ON public.local_content FOR SELECT USING (true);
CREATE POLICY "Admin write" ON public.local_events FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Public read" ON public.local_events FOR SELECT USING (true);
CREATE POLICY "Admin gestiona lugares" ON public.local_places FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Lectura publica de lugares" ON public.local_places FOR SELECT USING (true);

CREATE POLICY "Authenticated users can delete materials" ON public.materials_library FOR DELETE USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can insert materials" ON public.materials_library FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can read materials" ON public.materials_library FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update materials" ON public.materials_library FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY admin_owner_reports ON public.owner_reports FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());

CREATE POLICY anyone_can_read_visible_events ON public.portal_events FOR SELECT USING (is_visible = true);
CREATE POLICY staff_can_manage_events ON public.portal_events FOR ALL USING (true);

CREATE POLICY pricing_rules_public_read ON public.pricing_rules FOR SELECT TO anon, authenticated USING (active = true);
CREATE POLICY pricing_rules_service_all ON public.pricing_rules FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY profiles_admin_all ON public.profiles FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());
CREATE POLICY profiles_self_select ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY profiles_self_update ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY profiles_service_all ON public.profiles FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY protocols_admin_all ON public.protocols FOR ALL TO authenticated USING (check_is_admin()) WITH CHECK (check_is_admin());
CREATE POLICY protocols_service_all ON public.protocols FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Admins gestionan reseñas" ON public.reviews FOR ALL USING (check_is_admin());
CREATE POLICY "Admins gestionan reviews" ON public.reviews FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY "Clients can submit reviews" ON public.reviews FOR INSERT TO authenticated WITH CHECK (profile_id = auth.uid());
CREATE POLICY "Reviews publicas" ON public.reviews FOR SELECT USING (true);

CREATE POLICY "Admin gestiona rutas" ON public.routes FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Lectura publica de rutas" ON public.routes FOR SELECT USING (true);

CREATE POLICY admin_read_traveler_records ON public.traveler_records FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));
CREATE POLICY traveler_records_service_all ON public.traveler_records FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Admins gestionan configuración" ON public.web_config FOR ALL USING (check_is_admin());
CREATE POLICY "Lectura publica de config web" ON public.web_config FOR SELECT USING (true);


-- ---------------------------------------------------------------------
-- 9. CRONS (pg_cron) — estado el 2026-09-10, todos activos
-- ---------------------------------------------------------------------
-- jobid 2  daily-request-review      0 8,9 * * *   net.http_post -> /functions/v1/request-review
-- jobid 3  cleanup-rate-limits       15 3 * * *    SELECT cleanup_old_rate_limits();
-- jobid 4  prune-ai-interaction-logs 15 3 * * *    SELECT public.prune_ai_interaction_logs();
-- jobid 5  expire-booking-holds      * * * * *     SELECT public.expire_booking_holds();
-- jobid 6  prune-traveler-records    30 3 * * *    SELECT public.prune_traveler_records();
-- jobid 7  daily-booking-reminders   0 8 * * *     net.http_post -> /functions/v1/send-booking-reminders
--
-- Ademas, FUERA de la base: Trigger.dev `tjm-jobs` x3
--   emails 09:00 · SES 10:00 · importacion iCal cada 30 min.
--
-- (Los net.http_post llevan la publishable key en el header; no se
--  reproduce aqui para no versionar claves.)


-- ---------------------------------------------------------------------
-- 10. ADVISORS DE SEGURIDAD EN EL MOMENTO DEL SNAPSHOT (deuda heredada)
-- ---------------------------------------------------------------------
-- INFO 0008 rls_enabled_no_policy: otp_codes, rate_limits (deliberado)
-- WARN 0011 function_search_path_mutable: 16 funciones sin search_path fijo
-- WARN 0014 extension_in_public: btree_gist, pg_net, vector
-- WARN 0028 anon_security_definer_function_executable:
--           check_is_admin, record_marketing_consent, submit_traveler_records
-- WARN 0029 authenticated_security_definer_function_executable: las mismas 3
-- WARN auth_leaked_password_protection: desactivada
--
-- Nada de esto lo introducen 0002 ni 0003; queda anotado para no
-- confundir deuda vieja con deuda nueva.


-- ---------------------------------------------------------------------
-- 11. BUG LATENTE ENCONTRADO EN EL SNAPSHOT (lo arregla 0003)
-- ---------------------------------------------------------------------
-- is_staff() e is_admin() NO tenian EXECUTE para el rol `authenticated`:
--   is_staff  ACL: {postgres=X/postgres,service_role=X/postgres}
--   is_admin  ACL: {postgres=X/postgres,service_role=X/postgres}
-- Una politica RLS que llama a una funcion exige EXECUTE al usuario que
-- consulta, asi que TODA politica basada en is_admin() reventaba con
-- "permission denied for function is_admin" para cualquier usuario del
-- navegador. Afectadas: apartment_instructions (ALL), blog_posts (ALL),
-- discount_codes (ALL), local_places (ALL), routes (ALL) — es decir, el
-- admin no podia escribir en blog, rutas ni lugares desde el panel.
-- (Las politicas basadas en check_is_admin() si funcionaban: esa si
--  tenia el GRANT.)
-- 0003_rol_staff.sql concede el EXECUTE a las dos.
