-- 0045 — Los negocios y lugares del PUEBLO que faltaban en local_places (22-sep-2026).
--
-- Antes solo había 22 filas y casi todas de Pozo Alcón o Quesada: la web hablaba de
-- servicios de fuera y se callaba lo que tiene Hinojares. Censo y fuentes en
-- clients/tio-jose-maria/projects/2026-09-13-plan-captacion/2026-09-22-censo-hinojares-negocios-y-que-hacer.md
-- (Aplicado el 22-sep con el conector; se deja aquí para el repo.)
insert into local_places (type, category, name, address, phone, web_url, excerpt, description) values
('turismo_activo','actividades','Tropicual — aceite ecológico de Hinojares','C. Veguetas, 23486 Hinojares','722 83 57 78','https://tropicual.com','La almazara del pueblo: aceite ecológico Picual y Royal, con catas guiadas por Lucía.','Familia de cuatro generaciones en Hinojares. Aceite de oliva virgen extra ecológico de las variedades Picual y Royal, esta última endémica de la zona. Premios en el Japan Olive Oil Prize 2025, el NY International 2026 y Evooleum. Hacen catas guiadas con Lucía, paseos por el olivar y un programa para apadrinar un olivo. Pregúntanos y te ponemos en contacto.'),
('turismo_activo','actividades','Centro Ecuestre CazorlAvatur','Ctra. de Huesa s/n, 23486 Hinojares (200 m del Hotel Valle del Turrilla)','685 31 49 22','https://cazorlavatur.com','Rutas a caballo desde el pueblo: salinas (1,5 h), Guadiana Menor (2,5 h), día entero a la Bolera.','En Hinojares desde 2004, junto al río Turrilla. Grupos de 2 a 7 personas, desde 8 años y hasta 90 kg, con explicación previa para quien no ha montado nunca. Rutas de 1,5 h por las Salinas de Chíllar, 2,5 h por el Guadiana Menor, media jornada por el Guadalentín, día entero al embalse de la Bolera y fines de semana de iniciación. 4,9 en Google con más de 230 opiniones.'),
('restaurante','gastronomía','Café Bar Social','Parque del Emigrante, 23486 Hinojares',null,null,'El bar del pueblo: tapas, tostadas y desayunos. Martes a domingo, 8:00 a 0:00 (lunes cierra).','El bar de Hinojares, en el Parque del Emigrante. Desayunos, tapas, croquetas y jamón a precio de pueblo. Abre de martes a domingo de 8:00 a 0:00; los lunes cierra. Terraza y acceso sin escalones.'),
('turismo_activo','actividades','Rafting en el Guadiana Menor (Gualay Aventura)','Punto de encuentro: puente de la A-315, Hinojares',null,'https://gualay.com/rafting-jaen/','Rafting familiar de 6 km que sale del puente de Hinojares, desde 35 € y a partir de 4 años.','Descenso de 6 km por el Guadiana Menor, aguas de clase I-II entre paisajes semidesérticos. Dura 2 horas y media, de las cuales hora y media en el río, e incluye neopreno, guía y fotos. Desde 35 euros por persona y a partir de 4 años. Temporada de otoño: del 16 de septiembre al 30 de octubre, todos los días a las 16:00. Se reserva con antelación.'),
('naturaleza','naturaleza','Salinas del Mesto y de Chíllar','Término municipal de Hinojares',null,null,'Salinas de manantial en un paisaje de lejano oeste. Sendero circular SL-A 199 de 6,7 km.','Dos salinas de agua de manantial, la de Chíllar al sur y la del Mesto al norte, en uso hasta 2007. De aquí salía la sal con la que se curaba el jamón de la zona. Se recorren por el sendero circular SL-A 199 (6,7 km) o a caballo. El paisaje, entre cárcavas y olivar, no se parece a nada más de la sierra.'),
('naturaleza','naturaleza','Piedra del Reloj','Frente a la cascada de la Vinatera, Hinojares',null,null,'Una roca de tres escalones que da la hora con su propia sombra.','Formación rocosa de tres escalones verticales situada frente a la cascada de la Vinatera. Por la posición de la sombra, en el pueblo se ha sabido siempre qué hora era. Se llega en el mismo paseo que el nacimiento del Turrillas.'),
('naturaleza','naturaleza','Mirador del Valle del Río Turrilla','JA-B200, entrada a Hinojares',null,null,'Mirador acondicionado a la entrada del pueblo, con el valle entero delante.','Mirador en la carretera JA-B200, en uno de los accesos a Hinojares, con vistas al valle del río Turrilla. Hay otro mirador con merendero en la calle Cuevas Nuevas, dentro del pueblo. Ambos, para el atardecer.'),
('patrimonio','cultura','Sendero SL-A 198: Hinojares - Aldea de Cuenca','Salida desde Hinojares',null,null,'5,6 km lineales hasta la aldea de Cuenca, donde nace el río Turrillas.','Sendero señalizado de 5,6 kilómetros que une el pueblo con la aldea de Cuenca, donde brota el manantial de Siete Fuentes y nace el río Turrillas. En la aldea se han encontrado restos romanos y árabes. Con lluvias recientes, la cascada de la Vinatera cae más de cien metros.');

-- Aventura Sport no está en Hinojares ni en Pozo Alcón: su base está en Quesada.
update local_places set
  address='Calle de la Carretera de Huesa, 4, 23480 Quesada (base) — actividades en el embalse de la Bolera',
  phone='620 35 00 65',
  description='Empresa de turismo activo con más de quince años de experiencia, con base en Quesada. Kayak y paddle surf en el embalse de la Bolera, barranquismo, rutas a caballo y paintball. 4,9 en Google con más de 650 opiniones.'
where name='Aventura Sport';
